{
 "title": "Alerts View",
 "description": "Alerts View dashboard provides provides multi level metrics regarding alerts and their states of warning,errors and critical as well as info",
 "tags": [
  "alerts",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "severity",
    "query": {
     "query": "label_values(ALERTS{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},severity)"
    }
   },
   {
    "name": "state",
    "query": {
     "query": "label_values(ALERTS{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},alertstate)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", severity=~\"critical\", alertstate=~\"$state|$^\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", severity=~\"error\", alertstate=~\"$state\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", severity=~\"warn\", alertstate=~\"$state\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", severity=~\"info\", alertstate=~\"$state\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Critical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "ALERTS{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", severity=~\"critical\", alertstate=~\"$state|$^\",}",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "ALERTS{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", severity=\"error\", alertstate=~\"$state|$^\",}",
       "legendFormat": "{{severity}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "ALERTS{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", severity=\"warn\", alertstate=~\"$state|$^\",}",
       "legendFormat": "{{severity}}"
      }
     ]
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ALERTS{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", severity=~\"info\", alertstate=~\"$state|$^\"}",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}