# docker-compose.yml
version: '3.7'

services:
  exporter:
    image: aerospike/aerospike-prometheus-exporter:latest
    networks:
    - aerospike
    container_name: exporter
    environment:
    - AS_HOST=host.docker.internal
    - AS_PORT=3000
    - "METRIC_LABELS=type='development',source='aerospike'"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - "9145:9145"

  prometheus:
    image: prom/prometheus:latest
    networks:
    - aerospike
    container_name: prometheus
    volumes:
    - source: prometheus_data
      target: /var/lib/prometheus/
      type: volume
    - source: ./easy-prometheus.yml
      target: /etc/prometheus/prometheus.yml
      type: bind
    - source: ./config/prometheus/aerospike_rules.yml
      target: /etc/prometheus/aerospike_rules.yml
      type: bind
    depends_on:
    - exporter
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - '9090:9090'

  alertmanager:
    image: prom/alertmanager
    networks:
    - aerospike
    container_name: alertmanager
    volumes:
    - source: alertmanager_data
      target: /alertmanager
      type: volume
    - source: ./config/prometheus/alertmanager.yml
      target: /etc/prometheus/alertmanager.yml
      type: bind
    command:
    - '--config.file=/etc/prometheus/alertmanager.yml'
    - '--storage.path=/alertmanager'
    ports:
    - "9093:9093"

  grafana:
    image: grafana/grafana:latest
    networks:
    - aerospike
    container_name: grafana
    volumes:
    - source: grafana_data
      target: /var/lib/grafana
      type: volume
    - source: ./config/grafana/dashboards/
      target: /var/lib/grafana/dashboards/
      type: bind
    - source: ./config/grafana/provisioning/
      target: /etc/grafana/provisioning/
      type: bind
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource
    depends_on:
    - prometheus
    ports:
    - "4000:3000"

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}

networks:
  aerospike:
    driver: bridge
