{
 "title": "Aerospike XDR Proxy Summary",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(aerospike_xdr_proxy_requests, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lag (ms)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_xdr_proxy_requests_lag{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Success Rate/Second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"success\"}[40s]))"
    }
   ]
  },
  {
   "title": "Error Rate/Second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"error\"}[40s]))"
    }
   ]
  },
  {
   "title": "Skipped Rate/Second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"skipped\"}[40s]))"
    }
   ]
  },
  {
   "title": "Parse Error Rate/Second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"skipped\"}[40s]))"
    }
   ]
  },
  {
   "title": "XDR Connections/Second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_connections{cluster_name=\"$cluster_name\"}[40s]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Success Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR records successfully handled.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"success\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Error Rate/Second",
   "type": "graph",
   "description": "Total incoming records processing error.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"error\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Skip Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR records skipped.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"skipped\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Parse Error Rate/Second",
   "type": "graph",
   "description": "Total incoming XDR record parsing error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",status=\"parse-error\"}[40s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "XDR to Connector Lag",
   "type": "graph",
   "description": "Maximum lag in record LUT (last update time) in Aerospike and the record reaching the connectors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(aerospike_xdr_proxy_requests_lag{cluster_name=\"$cluster_name\"})",
     "legendFormat": "Maximum Lag"
    }
   ]
  },
  {
   "title": "Median Request Handling Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_xdr_proxy_requests_total{cluster_name=\"$cluster_name\",quantile=\"0.5\"} * 1000)",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Median Incoming XDR Record Size ",
   "type": "graph",
   "description": "Size of the incoming Aerospike XDR records in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(aerospike_xdr_proxy_record_payload_size{cluster_name=\"$cluster_name\",quantile=\"0.5\"})\n",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "XDR Connections Rate/Second",
   "type": "graph",
   "description": "Rate of Connections from Aerospike XDR to the connectors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum  ( \n    rate(aerospike_xdr_proxy_connections{cluster_name=\"$cluster_name\"}[40s])\n)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}