{
 "title": "Aerospike XDR Proxy Instances",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aerospike_xdr_proxy_requests, instance)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(aerospike_xdr_proxy_requests, cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate/Second",
   "type": "graph",
   "description": "Incoming XDR records successfully handled.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",instance=~\"$instance\",status=\"success\"}[40s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate/Second",
   "type": "graph",
   "description": "Incoming XDR records processing error.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",instance=~\"$instance\",status=\"error\"}[40s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Skip Rate/Second",
   "type": "graph",
   "description": "Incoming XDR records skipped.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",instance=~\"$instance\",status=\"skipped\"}[40s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Parse Error Rate/Second",
   "type": "graph",
   "description": "Incoming XDR record parsing error.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=\"$cluster_name\",instance=~\"$instance\",status=\"parse-error\"}[40s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Median Request Handling Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_proxy_requests_total{cluster_name=\"$cluster_name\",instance=~\"$instance\",quantile=\"0.5\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Median Incoming XDR Record Size ",
   "type": "graph",
   "description": "Size of the incoming Aerospike XDR records in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_proxy_record_payload_size{cluster_name=\"$cluster_name\",instance=~\"$instance\",quantile=\"0.5\"}\n",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "XDR to Connector Lag",
   "type": "graph",
   "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aerospike_xdr_proxy_requests_lag{cluster_name=\"$cluster_name\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "XDR Connections Rate/Second",
   "type": "graph",
   "description": "Rate of Connections from Aerospike XDR to the connector.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) ( \n    rate(aerospike_xdr_proxy_connections{cluster_name=\"$cluster_name\",instance=~\"$instance\"}[40s])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}