{
 "title": "All Flash",
 "tags": [ "all_flash" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   {
    "name": "latency_time_bucket",
    "label": "Latencies >",
    "query": "1,2,4,8,16,32,64,128,256,512,1024,2048,4096,16284,32768,65536"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Objects per Sprig",
   "type": "stat",
   "description": "Displays Average objects per sprig in each Namespace, formula is: (master_objects/4096) / partition_tree_sprigs.\npartition_tree_springs default value is 256",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ns) (\n    (\n    (aerospike_namespace_master_objects {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} / 4096) \n    / \n    (aerospike_namespace_partition_tree_sprigs{cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n)\nand aerospike_namespace_index_flash_used_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "HWM Breached",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ( \n    aerospike_namespace_hwm_breached {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} \nand \n    aerospike_namespace_index_flash_used_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} )>0",
     "legendFormat": "{{service}}:{{ns}}"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ( \n    aerospike_namespace_stop_writes {cluster_name=\"$cluster\", service=~\"$node|$^\"} \nand \n    aerospike_namespace_index_flash_used_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} ) >0",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "% Index  - Alloc, Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_namespace_index_flash_alloc_pct{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}:{{ns}} : Allocated"
    },
    {
     "expr": "aerospike_namespace_index_flash_used_pct{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}:{{ns}} - Used"
    }
   ]
  },
  {
   "title": "% Index  - Alloc, Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_namespace_index_flash_alloc_pct{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}:{{ns}} : Allocated"
    },
    {
     "expr": "aerospike_namespace_index_flash_used_pct{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}:{{ns}} - Used"
    }
   ]
  },
  {
   "title": "Used Memory Pct vs High Water Mark Pct",
   "type": "timeseries",
   "description": "Represents how much used memory is consumed against the High Water Memory configured, the lower it is the better",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "# memory used\n(((aerospike_namespace_index_flash_used_pct{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})\n/\n# high water mark\naerospike_namespace_index_type_mounts_high_water_pct{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}) * 100\n)\n",
     "legendFormat": "{{service}}:{{ns}}"
    }
   ]
  },
  {
   "title": "Average Object per Sprig",
   "type": "timeseries",
   "description": "Displays Average objects per sprig in each Namespace, formula is: (master_objects/4096) / partition_tree_sprigs.\npartition_tree_springs default value is 256",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n    (aerospike_namespace_master_objects {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} / 4096) \n    / \n    (aerospike_namespace_partition_tree_sprigs{cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n)\nand aerospike_namespace_index_flash_used_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n",
     "legendFormat": "{{service}}:{{ns}} "
    }
   ]
  },
  {
   "title": "Latencies > $latency_time_bucket ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n    (aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=\"+Inf\"})\n    - ignoring (le)\n    (aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=\"$latency_time_bucket\"})\n) and aerospike_namespace_index_flash_alloc_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}} - {{ns}} - Write "
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Evictions (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (service) (\n    rate(aerospike_namespace_evicted_objects{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n    and  \n    aerospike_namespace_index_flash_alloc_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Evicted Objects"
    }
   ]
  },
  {
   "title": "Stop Writes (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (service, ns) (\n    rate(aerospike_namespace_stop_writes{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval] )\n    and \n    aerospike_namespace_index_flash_used_pct {cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} )",
     "legendFormat": "{{service}} : {{ns}}"
    }
   ]
  }
 ]
}