{
 "title": "Jobs View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\" },ns)"
    }
   },
   {
    "name": "set",
    "label": "Set",
    "query": {
     "query": "label_values(aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", ns=~\"$namespace|$^\" },set)"
    }
   },
   {
    "name": "job_id",
    "label": "Job ID",
    "query": {
     "query": "label_values(aerospike_jobs_job_progress{job=\"$job_name\", cluster_name=~\"$cluster|$^\", ns=~\"$namespace|$^\", set=~\"$set|$^\" },trid)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<b>NOTE</b>: This dashboard will be deprecared in future "
   }
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job ID",
   "type": "text",
   "description": "Job ID",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "options": {
    "content": "<center><h1 style=\"color:#299c46;\">$job_id</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since done",
   "type": "stat",
   "description": "How long ago the scan finished, in milliseconds",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_jobs_time_since_done{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "time_since_done"
    }
   ]
  },
  {
   "title": "Job Type",
   "type": "stat",
   "description": "Job Type",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_jobs_job_progress{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "description": "Records per second requested for scan",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_rps{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "stat",
   "description": "Number of threads currently processing the scan",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_active_threads{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "Active Threads"
    }
   ]
  },
  {
   "title": "Job Progress",
   "type": "gauge",
   "description": "Estimated scan completion percentage",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_jobs_job_progress{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "job_progress"
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "stat",
   "description": "How long the scan has taken",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_jobs_run_time{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "run_time"
    }
   ]
  },
  {
   "title": "No. of partitions requested",
   "type": "stat",
   "description": "Number of partitions requested for the scan.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_n_pids_requested{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "n_pids_requested"
    }
   ]
  },
  {
   "title": "Records Throttled",
   "type": "stat",
   "description": "Number of records examined by the scan for throttling purposes",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_recs_throttled{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "recs_throttled"
    }
   ]
  },
  {
   "title": "Records Filtered",
   "type": "stat",
   "description": "Number of records filtered out by an expression at the metadata level\n\nNumber of records filtered out by an expression at the bin level",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_recs_filtered_meta{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "At Metadata Level"
    },
    {
     "expr": "sum(aerospike_jobs_recs_filtered_bins{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "At Bin Level"
    }
   ]
  },
  {
   "title": "Records Success / Failed",
   "type": "stat",
   "description": "Number of records successfully processed by the scan\n\nNumber of records that failed processing (e.g. unreadable)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_recs_failed{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(aerospike_jobs_recs_succeeded{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Net IO Bytes",
   "type": "stat",
   "description": "Amount of response data sent, in bytes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_jobs_net_io_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "net_io_bytes"
    }
   ]
  },
  {
   "title": "Socket Timeout",
   "type": "stat",
   "description": "Socket timeout in milliseconds",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_jobs_socket_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"$set\", trid=~\"$job_id\"})",
     "legendFormat": "socket_timeout"
    }
   ]
  }
 ]
}