{
 "title": "Set Dashboard",
 "description": "Set dashboard provides specific set level metrics as well as helping in tracking and setting specific set quotas.",
 "tags": [ "set" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   {
    "name": "set",
    "query": {
     "query": "label_values(aerospike_sets_device_data_bytes{ns=~\"$namespace\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },set)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Set: $set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "set" },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Device and memory for a set. ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aerospike_sets_device_data_bytes{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} ",
     "legendFormat": "Device {{service}} "
    },
    {
     "expr": " aerospike_sets_memory_data_bytes{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} ",
     "legendFormat": "Memory {{service}}"
    },
    {
     "expr": "aerospike_sets_stop_writes_size{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} ",
     "legendFormat": "{{set}} Limit "
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_sets_objects{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}",
     "legendFormat": "Objects"
    },
    {
     "expr": "aerospike_sets_tombstones{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}",
     "legendFormat": "Tombstones"
    },
    {
     "expr": "aerospike_sets_truncate_lut{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}",
     "legendFormat": "Truncations"
    },
    {
     "expr": "aerospike_sets_stop_writes_count{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}",
     "legendFormat": "Truncations"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "aerospike_sets_index_populating{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} ",
     "legendFormat": "Indexes Populating on {{service}}"
    },
    {
     "expr": "aerospike_sets_sindexes{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}",
     "legendFormat": "Secondary Indexes on {{service}}"
    }
   ]
  },
  {
   "title": "Disable Eviction",
   "type": "stat",
   "description": "More details about [disable eviction](https://docs.aerospike.com/reference/configuration#disable-eviction).",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_disable_eviction{set=~\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\", ns=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enable index",
   "type": "stat",
   "description": "More details about [enable index](https://docs.aerospike.com/reference/configuration#enable-index).",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_enable_index{set=~\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\", ns=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stop Writes Count",
   "type": "stat",
   "description": "More details about [stop writes count](https://docs.aerospike.com/reference/configuration#stop-writes-count).",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_stop_writes_count{set=~\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\", ns=~\"$namespace\"}",
     "legendFormat": "Stop Writes Count"
    }
   ]
  },
  {
   "title": "Stop Writes Size",
   "type": "stat",
   "description": "More details about [stop writes size](https://docs.aerospike.com/reference/configuration#stop-writes-size).",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_sets_stop_writes_size{set=~\"$set\", cluster_name=\"$cluster\",  job=\"$job_name\"}",
     "legendFormat": "Stop Writes Count"
    }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "bargauge",
   "description": "Namespace storage usage in percentage",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((aerospike_sets_device_data_bytes{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} + aerospike_sets_memory_data_bytes{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} ) / (aerospike_sets_stop_writes_size{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}!=0) * 100)",
     "legendFormat": "Size"
    },
    {
     "expr": "((aerospike_sets_objects{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} + aerospike_sets_tombstones{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"} ) / (aerospike_sets_stop_writes_count{set=~\"$set\", cluster_name=\"$cluster\", ns=~\"$namespace\", job=\"$job_name\"}!=0) * 100)",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}