groups:
  - name: aerospike.rules
    rules:
    - alert: ExporterAgentDown
      expr: up{job="aerospike"} == 0
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: '{{ $labels.instance }} has been down for more than 30 seconds.'
        summary: Node {{ $labels.instance }} down
    - alert: AerospikeNodeDown
      expr: aerospike_node_up{job="aerospike"} == 0
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: '{{ $labels.instance }} node is down.'
        summary: Node {{ $labels.instance }} down
    - alert: NamespaceStopWrites
      expr: aerospike_namespace_stop_writes{job="aerospike"} == 1
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Used diskspace for namespace {{ $labels.ns }} in node {{ $labels.instance }} is above stop writes limit.'
        summary: Stop Writes for {{ $labels.instance }}/{{ $labels.ns }}
    - alert: NamespaceMemoryCloseToStopWrites
      expr: (aerospike_namespace_stop_writes_pct{job="aerospike"} - (100 - aerospike_namespace_memory_free_pct{job="aerospike"})) <= 10
      for: 30s
      labels:
        severity: "2"
      annotations:
        description: 'Free memory for namespace {{ $labels.ns }} in node {{ $labels.instance }} is close to stop writes limit.'
        summary: Close to stop writes for {{ $labels.instance }}/{{ $labels.ns }} due to memory
    - alert: NamespaceDiskCloseToStopWrites
      expr: (aerospike_namespace_device_available_pct{job="aerospike"} - aerospike_namespace_storage_engine_min_avail_pct{job="aerospike"}) <= 10
      for: 30s
      labels:
        severity: "2"
      annotations:
        description: 'device_available_pct for namespace {{ $labels.ns }} in node {{ $labels.instance }} is close to min-avail-pct (stop writes) limit.'
        summary: Close to stop writes for {{ $labels.instance }}/{{ $labels.ns }} due to device_available_pct
    - alert: NamespacePmemCloseToStopWrites
      expr: (aerospike_namespace_pmem_available_pct{job="aerospike"} - aerospike_namespace_storage_engine_min_avail_pct{job="aerospike"}) <= 10
      for: 30s
      labels:
        severity: "2"
      annotations:
        description: 'pmem_available_pct for namespace {{ $labels.ns }} in node {{ $labels.instance }} is close to min-avail-pct (stop writes) limit.'
        summary: Close to stop writes for {{ $labels.instance }}/{{ $labels.ns }} due to pmem_available_pct
    - alert: ClockSkewStopWrites
      expr: aerospike_namespace_clock_skew_stop_writes{job="aerospike"} == 1
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Clock has skewed for namespace {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: Writes will be stopped by Aerospike
    - alert: ClusterSize
      expr: aerospike_node_stats_cluster_size{job="aerospike"} < 3 # user has to replace 3 here with their desired cluster size.
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Cluster size mismatch for namespace {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: Some of the node(s) has gone out of the cluster
    - alert: DeadPartitions
      expr: aerospike_namespace_dead_partitions{job="aerospike"} > 0
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Some of the partition(s) for namespace {{ $labels.ns }} in node {{ $labels.instance }} are dead'
        summary: Will require the use of the revive command to make them available again
    - alert: HwmBreached
      expr: aerospike_namespace_hwm_breached{job="aerospike"} == 1
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'High water mark has breached for namespace {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: Eviction will start to make the space available
    - alert: UnavailablePartitions
      expr: aerospike_namespace_unavailable_partitions{job="aerospike"} > 0
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Some of the partition(s) is not available for namespace {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: Server could not find some partition(s). Check for the network issues and make sure cluster forms properly
    - alert: XDRTimelag
      expr: aerospike_node_stats_xdr_timelag{job="aerospike"} > 10 # (Aerospike 4.9 and older) user can configure the seconds. Refer XDR throttling
      for: 30s
      labels:
        severity: "2"
      annotations:
        description: 'There seems some lag in XDR for namespace {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: Lag can be there in XDR due to network connectivity issues or errors writing at a destination cluster
    - alert: XDRTimelag
      expr: aerospike_xdr_lag{job="aerospike"} > 10 # (Aerospike 5.0 and later) user can configure the seconds. Refer XDR throttling
      for: 30s
      labels:
        severity: "2"
      annotations:
        description: 'There seems some lag in XDR for namespace {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: Lag can be there in XDR due to network connectivity issues or errors writing at a destination cluster
    - alert: ActiveProxies
      expr: (increase(aerospike_namespace_client_proxy_complete{job="aerospike"}[2m]) + increase(aerospike_namespace_client_proxy_timeout{job="aerospike"}[2m]) + increase(aerospike_namespace_client_proxy_error{job="aerospike"}[2m]) + increase(aerospike_namespace_batch_sub_proxy_complete{job="aerospike"}[2m]) + increase(aerospike_namespace_batch_sub_proxy_timeout{job="aerospike"}[2m]) + increase(aerospike_namespace_batch_sub_proxy_error{job="aerospike"}[2m])) > 0
      for: 30s
      labels:
        severity: "2"
      annotations:
        description: 'Active proxies detected for {{ $labels.ns }} on node {{ $labels.instance }}'
        summary: Node is doing proxy. Proxies can happen during cluster change / migrations or if there are any network issues.
    - alert: NamespaceSupervisorFallingBehind
      expr: aerospike_namespace_nsup_cycle_deleted_pct{job="aerospike"} > 1 # (Aerospike 6.3 and later) 
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'There seems some lag falling behind and/or display the length of time the most recent NSUP cycle lasted {{ $labels.ns }} in node {{ $labels.instance }}'
        summary: NSUP is falling behind and/or display the length of time the most recent NSUP cycle lasted
    - alert: NamespaceFreeMemoryCloseToStopWrites
      expr: (aerospike_namespace_stop_writes_sys_memory_pct{job="aerospike"} - scalar(100 - (aerospike_node_stats_system_free_mem_pct{job="aerospike"}))) <= 10
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Free memory for namespace {{ $labels.ns }} in node {{ $labels.instance }} is close to stop writes limit.'
        summary: Close to stop writes for {{ $labels.instance }}/{{ $labels.ns }} due to memory
    - alert: NamespaceSetQuotaWarning
      expr: (((aerospike_sets_device_data_bytes{job="aerospike"} + aerospike_sets_memory_data_bytes{job="aerospike"}) / (aerospike_sets_stop_writes_size{job="aerospike"} != 0)) * 100) > 80
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'Nearing memory quota for {{ $labels.set }} in namespace {{ $labels.ns }} in node {{ $labels.instance }}.'
        summary: One of your nodes is at 80% of the quota you have configured on the set.
    - alert: NamespaceSetQuotaAlert
      expr: (((aerospike_sets_device_data_bytes{job="aerospike"} + aerospike_sets_memory_data_bytes{job="aerospike"}) / (aerospike_sets_stop_writes_size{job="aerospike"} != 0)) * 100) > 99
      for: 30s
      labels:
        severity: "1"
      annotations:
        description: 'At or Above memory quota for {{ $labels.set }} in namespace {{ $labels.ns }} in node {{ $labels.instance }}.'
        summary: One of your nodes is at 99% of the quota you have configured on the set.
