{
 "title": "Secret Agent",
 "description": "Secret Agents dashboard helps visualise connections, churn rate, and errors of connections across multiple agents",
 "tags": [
  "secret_agent",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_sa_connections_active,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_up{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(aerospike_sa_connections_active{job=\"$job_name\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   {
    "name": "as_metrics_base_url",
    "query": "https://docs.aerospike.com/tools/secret-agent/metrics"
   },
   {
    "name": "as_configs_base_url",
    "query": "https://docs.aerospike.com/tools/secret-agent/metrics"
   },
   { "name": "latencies", "label": "Latencies >", "query": "4" }
  ]
 },
 "panels": [
  {
   "title": "Secret Agents (count)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (aerospike_sa_connections_active))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Secret Agent success (rate) (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (module) (rate(aerospike_sa_success{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Connections active (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (module) (aerospike_sa_connections_active{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Connections error (rate) (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (module) (rate(aerospike_sa_connections_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Fetch Latency P50",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_sa_fetch_latency_p50{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_sa_fetch_latency_p50{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_sa_fetch_latency_p50{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Listener Error (rate) (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (module) (rate(aerospike_sa_write_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Write {{module}}"
    },
    {
     "expr": "sum by (module) (rate(aerospike_sa_tls_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Tls {{module}}"
    },
    {
     "expr": "sum by (module) (rate(aerospike_sa_read_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Read {{module}}"
    }
   ]
  },
  {
   "title": "Secret Agent Error (rate) (total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (module) (rate(aerospike_sa_fetch_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "fetch {{module}}"
    },
    {
     "expr": "sum by (module) (rate(aerospike_sa_resource_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Resource {{module}}"
    },
    {
     "expr": "sum by (module) (rate(aerospike_sa_session_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Session {{module}}"
    }
   ]
  },
  {
   "title": "Fetch Latency P95",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_sa_fetch_latency_p95{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_sa_fetch_latency_p95{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_sa_fetch_latency_p95{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Secret Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate) ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": " rate(aerospike_sa_success{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{module}}"
      }
     ]
    },
    {
     "title": "Errors (rate) ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": " rate(aerospike_sa_resource_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{module}} : Resource"
      },
      {
       "expr": " rate(aerospike_sa_fetch_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{module}} : Fetch"
      },
      {
       "expr": " rate(aerospike_sa_key_not_found_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{module}} : Parse"
      },
      {
       "expr": " rate(aerospike_sa_session_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{module}} : Session"
      },
      {
       "expr": " rate(aerospike_sa_role_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}/{{module}} : Role"
      }
     ]
    },
    {
     "title": "Fatch Latencies P50 & P95",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(aerospike_sa_fetch_latency_p50{job=~\"$job_name\", instance=~\"$node\"} )",
       "legendFormat": "{{instance}}/{{module}} p50"
      },
      {
       "expr": " aerospike_sa_fetch_latency_p95{job=~\"$job_name\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}/{{module}} p95"
      }
     ]
    }
   ]
  },
  { "title": "Listeners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Connections Open & Closed (rate) ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate (aerospike_sa_connections_opened{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{module}} : Error"
    },
    {
     "expr": "rate (aerospike_sa_connections_closed{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval]) * -1",
     "legendFormat": "{{instance}}/{{module}} : Closed"
    }
   ]
  },
  {
   "title": "Connections - Active ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": " (aerospike_sa_connections_active{job=~\"$job_name\", instance=~\"$node\"})",
     "legendFormat": "{{instance}}/{{module}} : Active"
    }
   ]
  },
  {
   "title": "Errors (rate) ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": " rate(aerospike_sa_read_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{module}} : Read"
    },
    {
     "expr": " rate(aerospike_sa_write_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{module}} : Write"
    },
    {
     "expr": " rate(aerospike_sa_parse_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{module}} : Parse"
    },
    {
     "expr": " rate(aerospike_sa_tls_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{module}} : TLS"
    },
    {
     "expr": " rate(aerospike_sa_connections_err{job=~\"$job_name\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}/{{module}} : Connections"
    }
   ]
  }
 ]
}