{
 "title": "Aerospike Graph Service",
 "description": "This dashboard helps to visualise the aerospike graphical service data.",
 "tags": [
  "Aerospike",
  "Graph Service",
  "monitoring",
  "aws"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_graph_service_process_max_fds,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Aerospike Cluster",
    "query": {
     "query": "label_values(aerospike_graph_service_cluster_name{job=~\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(aerospike_graph_service_cluster_name{job=~\"$job_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Graph Service (count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "neo4j_instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aerospike_graph_service_cluster_name{job=~\"$job_name\"})",
     "legendFormat": "AGS Count"
    }
   ]
  },
  {
   "title": "Total vCPU Hours",
   "type": "stat",
   "description": "total vcpu hours",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_graph_service_usage{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Service Usage"
    }
   ]
  },
  {
   "title": "FD Open",
   "type": "bargauge",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_graph_service_process_open_fds{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_graph_service_process_open_fds{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_graph_service_process_open_fds{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "bargauge",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_graph_service_process_resident_memory_bytes{job=~\"$job_name\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_graph_service_process_resident_memory_bytes{job=~\"$job_name\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_graph_service_process_resident_memory_bytes{job=~\"$job_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Supernode Traversed (count)",
   "type": "stat",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_graph_service_supernode_traversed_count{job=~\"$job_name\", })",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Query Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*avg(aerospike_graph_service_GremlinServer_op_traversal{job=~\"$job_name\", instance=~\"$instance\"}) by (quantile)",
     "legendFormat": "P{{quantile}} "
    }
   ]
  },
  {
   "title": "Script Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*avg(aerospike_graph_service_GremlinServer_op_eval{job=~\"$job_name\", instance=~\"$instance\"}) by (quantile)",
     "legendFormat": "P{{quantile}} "
    }
   ]
  },
  {
   "title": "Queries/Second",
   "type": "timeseries",
   "description": "The total number of Traversal bytecode-based executions count",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_graph_service_GremlinServer_op_traversal_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "    "
    }
   ]
  },
  {
   "title": "Scripts/Second",
   "type": "timeseries",
   "description": "The total number of script evaluations count.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_graph_service_GremlinServer_op_eval_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "  "
    }
   ]
  },
  {
   "title": "Gremlin Server Sessions",
   "type": "timeseries",
   "description": "Average time spent compiling new scripts for the session with engine.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aerospike_graph_service_GremlinServer_sessions{job=~\"$job_name\", instance=~\"$instance\"}) ",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Errors (rate)",
   "type": "timeseries",
   "description": "The total number of errors",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_graph_service_GremlinServer_errors_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>JVM</b></p>"
   }
  },
  {
   "title": "% Heap Used (max)",
   "type": "stat",
   "description": "The maximum heap used memory.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((aerospike_graph_service_jvm_memory_bytes_used{job=~\"$job_name\", instance=~\"$instance\", area=~\"heap\"})*100 / (aerospike_graph_service_jvm_memory_bytes_max{job=~\"$job_name\", instance=~\"$instance\", area=~\"heap\"}))",
     "legendFormat": "Heap used max"
    }
   ]
  },
  {
   "title": "Current Threads(total)",
   "type": "stat",
   "description": "Current count of JVM threads.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_graph_service_jvm_threads_current{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "current threads"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "gauge",
   "description": "Used bytes of a given JVM memory area",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_graph_service_jvm_memory_bytes_used{job=~\"$job_name\", instance=~\"$instance\", area=~\".*\"}) by (area)",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Objects waiting",
   "type": "bargauge",
   "description": "The number of objects waiting in the finalizer queue.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Aerospike Cluster Name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " group by (cluster_name)(aerospike_graph_service_cluster_name{job=~\"$job_name\", cluster_name=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "JVM version",
     "type": "stat",
     "description": "VM version info",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_info{job=~\"$job_name\",instance=~\"$instance\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "stat",
     "description": "Total Loaded - The total number of classes that have been loaded since the JVM has started execution.\n\nCurrently Loaded - The number of classes that are currently loaded in the JVM.\n\nTotal Unloaded - The total number of classes that have been unloaded since the JVM has started execution.\n",
     "gridPos": { "h": 4, "w": 9, "x": 10, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_loaded_total{job=~\"$job_name\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Total Loaded"
      },
      {
       "expr": "aerospike_graph_service_jvm_classes_currently_loaded{job=~\"$job_name\",instance=~\"$instance\"}",
       "legendFormat": "Currently Loaded"
      },
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_unloaded_total{job=~\"$job_name\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Total Unloaded"
      }
     ]
    },
    {
     "title": "Supernode Traversed (count)",
     "type": "stat",
     "description": "refers how many times supernode is traversed",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_graph_service_supernode_traversed_count{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "Currently Loaded"
      }
     ]
    },
    {
     "title": "Process CPU Usage (rate in CPU-Seconds)",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_process_cpu_seconds_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Resident memory (bytes)",
     "type": "timeseries",
     "description": "Resident memory size in bytes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_process_resident_memory_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Total Errors (rate)",
     "type": "timeseries",
     "description": "The number of total errors",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_GremlinServer_errors_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Sessions (rate)",
     "type": "timeseries",
     "description": "The number of sessions open at the time the metric was last measured.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_GremlinServer_sessions{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Cache Total Load Time",
     "type": "timeseries",
     "description": "Total number of nanoseconds that the cache spent compiling scripts for the session with engine.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_total_load_time{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Cache Average Load Penalty",
     "type": "timeseries",
     "description": "Average time spent compiling new scripts for the session with engine.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_average_load_penalty{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Cache Load Success Count",
     "type": "timeseries",
     "description": "Total number of times the cache lookup method succeeded to compile a new script for the session with engine.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_load_success_count{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Cache Load Failure",
     "type": "timeseries",
     "description": "Load failure count - Total number of times the cache lookup method failed to compile a new script for the session with engine.\n\nLoad failure rate - Ratio of script compilation attempts that failed for the session with engine.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_load_failure_count{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "count"
      },
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_load_failure_rate{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "rate"
      }
     ]
    },
    {
     "title": "Cache Eviction",
     "type": "timeseries",
     "description": "Eviction Count - Number of times a script compiled to a class has been evicted from the cache for the session with engine.\n\nEviction weight - Sum of the weights of evicted entries from the class cache for the session with engine.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_eviction_count{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "Count"
      },
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_eviction_weight{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "Weight"
      }
     ]
    },
    {
     "title": "Cache Long Run compilation",
     "type": "timeseries",
     "description": "Number of compilations that extended beyond the expected compilation time for the session with engine.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_GremlinServer_gremlin_groovy_sessionless_class_cache_long_run_compilation_count{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Total Throughput",
     "type": "timeseries",
     "description": "The total throughput",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_GremlinServer_op_eval_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])+ rate(aerospike_graph_service_GremlinServer_op_traversal_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "   "
      }
     ]
    },
    {
     "title": "Operations/Second",
     "type": "timeseries",
     "description": "The total number of Traversal and Eval bytecode-based executions count",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(rate(aerospike_graph_service_GremlinServer_op_traversal_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Traversal"
      },
      {
       "expr": "(rate(aerospike_graph_service_GremlinServer_op_eval_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Eval"
      }
     ]
    },
    {
     "title": "Query  Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1000*avg(aerospike_graph_service_GremlinServer_op_traversal{job=~\"$job_name\", instance=~\"$instance\"}) by (quantile)",
       "legendFormat": "P{{quantile}}"
      }
     ]
    },
    {
     "title": "Script Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "1000*avg(aerospike_graph_service_GremlinServer_op_eval{job=~\"$job_name\", instance=~\"$instance\"}) by (quantile)",
       "legendFormat": "P{{quantile}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 71 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Threads - JVM</b></p>"
     }
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Current, Daemon, peak, started thread count of a JVM.\nDeadlocked - Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_threads_current{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "current"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_daemon{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "daemon"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_peak{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "peak"
      },
      {
       "expr": "rate(aerospike_graph_service_jvm_threads_started_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "started"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_deadlocked{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "deadlocked"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_deadlocked_monitor{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "deadlocked_monitor"
      }
     ]
    },
    {
     "title": "Threads state",
     "type": "timeseries",
     "description": "Current count of threads by state.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_threads_state{job=~\"$job_name\", instance=~\"$instance\" })",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 78 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Memory - JVM</b></p>"
     }
    },
    {
     "title": "Committed memory (bytes)",
     "type": "timeseries",
     "description": "Committed (bytes) of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_committed{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Initial memory (bytes)",
     "type": "timeseries",
     "description": "Initial bytes of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_init{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Max memory (bytes)",
     "type": "timeseries",
     "description": "Max (bytes) of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_max{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Used memory (bytes)",
     "type": "timeseries",
     "description": "Used bytes of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_used{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Memory Pool - JVM</b></p>"
     }
    },
    {
     "title": "Allocated (bytes)(rate)",
     "type": "timeseries",
     "description": "Total bytes allocated in a given JVM memory pool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_memory_pool_allocated_bytes_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Created (bytes)(rate)",
     "type": "timeseries",
     "description": "Total bytes allocated in a given JVM memory pool. Only updated after GC, not continuously.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_memory_pool_allocated_bytes_created{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Initial (bytes)",
     "type": "timeseries",
     "description": "Initial bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_init{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Committed (bytes)",
     "type": "timeseries",
     "description": "Committed bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_committed{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Used (bytes)",
     "type": "timeseries",
     "description": "Used bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_used{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Max (bytes)",
     "type": "timeseries",
     "description": "Max bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_max{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 112 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Memory Pool Collection - JVM</b></p>"
     }
    },
    {
     "title": "Init (bytes)",
     "type": "timeseries",
     "description": "Initial after last collection bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_init_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Committed (bytes)",
     "type": "timeseries",
     "description": "Committed after last collection bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_committed_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Used (bytes)",
     "type": "timeseries",
     "description": "Used bytes after last collection of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_used_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Max (bytes)",
     "type": "timeseries",
     "description": "Max bytes after last collection of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_max_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 126 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Objects - JVM</b></p>"
     }
    },
    {
     "title": "Load",
     "type": "timeseries",
     "description": "Total Loaded - The total number of classes that have been loaded since the JVM has started execution.\n\nTotal Unloaded - The total number of classes that have been unloaded since the JVM has started execution.\n\nCurrently Loaded - The number of classes that are currently loaded in the JVM.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_loaded_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "loaded"
      },
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_unloaded_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Unloaded"
      },
      {
       "expr": "aerospike_graph_service_jvm_classes_currently_loaded{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Objects waiting",
     "type": "timeseries",
     "description": "The number of objects waiting in the finalizer queue.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 134 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Buffer Pool - JVM</b></p>"
     }
    },
    {
     "title": "Used bytes",
     "type": "timeseries",
     "description": "Used bytes of a given JVM buffer pool.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_buffer_pool_used_bytes{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Used buffers",
     "type": "timeseries",
     "description": "Used buffers of a given JVM buffer pool.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_buffer_pool_used_buffers{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Bytes Capacity",
     "type": "timeseries",
     "description": "Bytes capacity of a given JVM buffer pool.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_buffer_pool_capacity_bytes{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 142 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Garbage Collector - JVM</b></p>"
     }
    },
    {
     "title": "GC count (rate)",
     "type": "timeseries",
     "description": "Time spent in a given JVM garbage collector in seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_gc_collection_seconds_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC sum (rate)",
     "type": "timeseries",
     "description": "Time spent in a given JVM garbage collector in seconds",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_gc_collection_seconds_sum{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}