version: "3.7"
services:

  exporter:
    image: aerospike/aerospike-prometheus-exporter:latest
    networks:
      - aerospike_otel_nw
    container_name: as_prom_exporter
    environment:
    - AS_HOST=host.docker.internal
    - AS_PORT=3000
    - "METRIC_LABELS=type='development',source='aerospike', latitude='36.778259', longitude='-119.417931' "
    extra_hosts:
    - "host.docker.internal:host-gateway"

  # Collector
  otel-collector:
    networks:
      - aerospike_otel_nw
    image: otel/opentelemetry-collector-contrib:latest
    container_name: as_otel_contrib
    privileged: true
    restart: always
    environment:
    - AWS_REGION=<AWS_REGION_LOCATION>
    - AWS_ACCESS_KEY_ID=<MENTION-YOUR-AWS-CLOUD-WATCH-KEY>
    - AWS_SECRET_ACCESS_KEY=<MENTION-YOUR-AWS-CW-SECRET-ACCESS-KEY>
    volumes:
    - source: ./cloudwatch-otel-collector-config.yml 
      target: /etc/otel-collector-config.yml 
      type: bind
    command: ["--config=/etc/otel-collector-config.yml"]

volumes:
  otel_prometheus_data: {}
  otel_data: {}
networks:
  aerospike_otel_nw:
    driver: bridge
