receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "as_otel_contrib:4317"

  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel_as_demos'
        scrape_interval: 15s
        static_configs:
          - targets: ['as_prom_exporter:9145']

exporters:
  prometheus:
    endpoint: "0.0.0.0:30145"

  datadog:
    api: 
      site: datadoghq.com
      key: <DATADOG-APP-KEY> 
    metrics:
     sums:
       cumulative_monotonic_mode: raw_value
processors:
  metricstransform:
    transforms:
      - include: ^aerospike_(.*)$$
        match_type: regexp
        action: update
        new_name: aerospike.aerospike_$$1
      - include: ^aerospike(.*)$$
        match_type: regexp
        action: update
        operations:
          - action: update_label
            label: service
            new_label: aerospike_service
          - action: update_label
            label: cluster_name
            new_label: aerospike_cluster
  batch:
        send_batch_max_size: 100
        send_batch_size: 10
        timeout: 10s

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog ]
    metrics:
      receivers: [prometheus ]
      processors: [metricstransform, batch]
      exporters: [prometheus, datadog]
