version: "3.7"
services:

  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server-enterprise:latest
#    volumes:
#      - .:/etc/aerospike
#      - "./aerospike.conf:/etc/aerospike/aerospike.conf"
#    command: [ "--config-file","/etc/aerospike/aerospike.conf" ]
    ports:
      - "3000:3000"

  exporter:
    image: aerospike/aerospike-prometheus-exporter:latest
    ports:
      - "9145:9145"
    networks:
      - aerospike_otel_nw
    container_name: as_prom_exporter
    environment:
    - AS_HOST=host.docker.internal
    - AS_PORT=3000
    - "METRIC_LABELS=type='development',source='aerospike', latitude='36.778259', longitude='-119.417931' "
    extra_hosts:
    - "host.docker.internal:host-gateway"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "30145:30145"
    networks:
      - aerospike_otel_nw
    container_name: as_otel_contrib
    
    privileged: true
    restart: always
    volumes:
    - source: ./datadog-otel-collector-config.yml 
      target: /etc/otel-collector-config.yml 
      type: bind
    command: ["--config=/etc/otel-collector-config.yml"]

volumes:
  otel_prometheus_data: {}
  otel_data: {}
networks:
  aerospike_otel_nw:
    driver: bridge
