{
 "title": "Aerospike Host View",
 "description": "This dashboard helps visualise the details like CPU, memory, Network etc of all the nodes.",
 "tags": [
  "linux",
  "Monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", cluster_name=\"$cluster_name\"}, instance)"
    }
   },
   { "name": "topk_limit", "label": "Top-K", "query": "10" },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Exporter UP (total)",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(group by (instance) (node_exporter_build_info{job=\"$job\",cluster_name=\"$cluster_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores (total)",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum( count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{job=\"$job\",cluster_name=\"$cluster_name\"}) ))",
     "legendFormat": "Total CPU cores"
    }
   ]
  },
  {
   "title": "CPU Cores ",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " min(count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{}) ))",
     "legendFormat": "Min"
    },
    {
     "expr": " avg(count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{}) ))",
     "legendFormat": "Avg"
    },
    {
     "expr": " max(count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{}) ))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total Memory (bytes) ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min  (node_memory_MemTotal_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Min "
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "File Descriptor (allocated)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " min(node_filefd_allocated{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Min"
    },
    {
     "expr": " avg(node_filefd_allocated{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": " max(node_filefd_allocated{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "% CPU Utilization (rate)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " min(sum by( instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_name=\"$cluster_name\",instance=~\"$node\", mode!=\"idle\"}[$__rate_interval])) / scalar(sum ( irate(node_cpu_seconds_total{job=\"$job\", cluster_name=\"$cluster_name\",instance=~\"$node\", }[$__rate_interval]) ))*100 ) ",
     "legendFormat": "Min "
    },
    {
     "expr": " avg(sum by( instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_name=\"$cluster_name\",instance=~\"$node\", mode!=\"idle\"}[$__rate_interval])) / scalar(sum ( irate(node_cpu_seconds_total{job=\"$job\", cluster_name=\"$cluster_name\",instance=~\"$node\", }[$__rate_interval]) ))*100 ) ",
     "legendFormat": "Avg"
    },
    {
     "expr": " max(sum by( instance) (irate(node_cpu_seconds_total{job=\"$job\", cluster_name=\"$cluster_name\",instance=~\"$node\", mode!=\"idle\"}[$__rate_interval])) / scalar(sum ( irate(node_cpu_seconds_total{job=\"$job\", cluster_name=\"$cluster_name\",instance=~\"$node\", }[$__rate_interval]) ))*100 ) ",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory (total ) (bytes) ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory (Unused ) (bytes) ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "Memory (Unused ) (bytes) ",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min (node_memory_MemFree_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Min "
    },
    {
     "expr": "avg (node_memory_MemFree_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max (node_memory_MemFree_bytes{job=\"$job\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Network Traffic - retransmit (packets) (total) (rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval] ))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic - Received (bytes) (rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_receive_bytes_total{job=\"$job\",cluster_name=\"$cluster_name\", instance=~\"$node\",}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic -Transmit (bytes) (rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_transmit_bytes_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic - drop (packets) (rate)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_transmit_drop_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval] ))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Cores (total)",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(count by (cpu) (node_cpu_seconds_total{job=\"$job\", instance=~\"$node\",cluster_name=\"$cluster_name\"}) )",
       "legendFormat": "CPU cores {{instance}}"
      }
     ]
    },
    {
     "title": "Memory (Unused ) (bytes) ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemFree_bytes{job=\"$job\",instance=~\"$node\",cluster_name=\"$cluster_name\"})",
       "legendFormat": "Unused {{instance}}"
      }
     ]
    },
    {
     "title": "Memory (total ) (bytes) ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{job=\"$job\",cluster_name=\"$cluster_name\", instance=~\"$node\"})",
       "legendFormat": "Total {{instance}}"
      }
     ]
    },
    {
     "title": "File Descriptor ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Maximum "
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Allocated"
      }
     ]
    },
    {
     "title": "% CPU Utilization (topk) (rate)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk($topk_limit, (sum by(cpu, instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\", mode!=\"idle\",cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])))) * 100)",
       "legendFormat": "Core {{cpu}}"
      }
     ]
    },
    {
     "title": "CPU Info (%) (rate)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\", cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\" ,cluster_name=\"$cluster_name\"}[$__rate_interval])))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\",cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\", mode=\"iowait\",cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\", mode=~\".*irq\",cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\", mode=\"idle\",cluster_name=\"$cluster_name\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Details (Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "(node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
       "legendFormat": "Unused"
      },
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory Page Faults (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "Pgfault"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "PgMajFault"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])  - irate(node_vmstat_pgmajfault{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "PgMinFault"
      }
     ]
    },
    {
     "title": "Memory Stack (Bytes)",
     "type": "timeseries",
     "description": "Apps- Memory used by user-space applications; PageTables- Memory used to map between virtual and physical memory addresses,SwapCache- Memory that keeps track of pages that have been fetched from swap but not yet been modified; Slab- Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc; Cache- Parked file data (file content) cache; Buffers- Block device (e.g. harddisk) cache; Unused- Free memory unassigned; Swap- Swap space used; Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_Buffers_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_Slab_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_PageTables_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_SwapCached_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Apps"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "PageTables"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "SwapCache"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Slab"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Unused"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"})",
       "legendFormat": "Swap"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Hardware Corrupted"
      }
     ]
    },
    {
     "title": "Memory Pages In / Out (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "PagesIn"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "PagesOut"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "PgSwapIn"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "PgSwapOut"
      }
     ]
    },
    {
     "title": "Disk IOps Completed (rate)",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes"
      }
     ]
    },
    {
     "title": "Disk R/W Data (Bytes) (rate)",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Written"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time (seconds) (rate)",
     "type": "timeseries",
     "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} -Read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} -Write"
      }
     ]
    },
    {
     "title": "Disk - Average Queue Size (rate)",
     "type": "timeseries",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk - I/O Utilization (%) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\",cluster_name=\"$cluster_name\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk - Time Spent Doing I/Os (%) (rate)",
     "type": "timeseries",
     "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - IO"
      },
      {
       "expr": "irate(node_disk_discard_time_seconds_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - discard"
      }
     ]
    },
    {
     "title": "Filesystem space available (Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Max "
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "TCP In / Out (rate)",
     "type": "timeseries",
     "description": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections; OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "InSegs"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "OutSegs"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "TCP connections"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dynamic is \"-1\")"
      }
     ]
    },
    {
     "title": "Network Traffic (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic by Bytes (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_multicast_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      }
     ]
    },
    {
     "title": "Network Traffic Errors (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Drop (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Retransmit (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": " (irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\",job=\"$job\",cluster_name=\"$cluster_name\"}[$__rate_interval] ))",
       "legendFormat": "{{instance}}"
      },
      { "legendFormat": "{{device}} - Transmit" }
     ]
    }
   ]
  }
 ]
}