{
 "title": "All Flash",
 "description": "Displays all critical metrics required to monitor when flash drive is configured for either sindex or index",
 "tags": [
  "all_flash",
  "usecase"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values({__name__=~ \"aerospike_namespace_index_type_mount_age|aerospike_namespace_sindex_type_mount_age\", job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\"}, ns)\n"
    }
   },
   {
    "name": "latency_time_bucket",
    "label": "Latencies >",
    "query": "1,2,4,8,16,32,64,128,256,512,1024,2048,4096,16284,32768,65536"
   },
   { "name": "topk_limit", "label": "Top-K", "query": "15" },
   {
    "name": "dont_use_namespace",
    "query": {
     "query": "label_values(aerospike_namespace_index_type_mount_age{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" } ,ns)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Objects per Sprig (Primary Index)",
   "type": "bargauge",
   "description": "Displays Average objects per sprig in each Namespace, formula is: (master_objects/4096) / partition_tree_sprigs.\npartition_tree_springs default value is 256",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min  (\n    (aerospike_namespace_master_objects {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} / 4096) \n    / \n    (aerospike_namespace_partition_tree_sprigs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "avg  (\n    (aerospike_namespace_master_objects {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} / 4096) \n    / \n    (aerospike_namespace_partition_tree_sprigs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max  (\n    (aerospike_namespace_master_objects {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} / 4096) \n    / \n    (aerospike_namespace_partition_tree_sprigs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Latencies > 4ms (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", ns=\"$namespace\", le=\"+Inf\"})\n- \nsum (aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", ns=\"$namespace\",  le=\"4\"}) ",
     "legendFormat": "Write > 4ms"
    },
    {
     "expr": "sum (aerospike_latencies_read_ms_bucket{cluster_name=~\"$cluster\", ns=\"$namespace\", le=\"+Inf\",}) \n- \nsum (aerospike_latencies_read_ms_bucket{cluster_name=~\"$cluster\", ns=\"$namespace\", le=\"4\",}) ",
     "legendFormat": "Read > 4ms"
    }
   ]
  },
  {
   "title": "HWM Breached (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_hwm_breached {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "Stop Writes (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_stop_writes {job=\"$job_name\", cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace\"})",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "Index Pressure ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(aerospike_namespace_index_pressure_total_memory {job=\"$job_name\", cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace\"})",
     "legendFormat": "{{ns}} : Total Memory"
    },
    {
     "expr": "(aerospike_namespace_index_pressure_dirty_memory {job=\"$job_name\", cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace\"})",
     "legendFormat": "{{ns}} : Dirty Memory"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Evictions (rate) (total)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": " sum by (service) (\n    rate(aerospike_namespace_evicted_objects{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Evicted Objects"
      }
     ]
    },
    {
     "title": "Stop Writes (rate) (total)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (service, ns) (\n    rate(aerospike_namespace_stop_writes{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval] )\n)",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "HWM Breaches (rate) (total)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (service, ns) (\n    rate(aerospike_namespace_hwm_breached {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval] )\n)",
       "legendFormat": "{{service}}/{{ns}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources - Primary Index - $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object per Sprig",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": " (\n    (aerospike_namespace_master_objects {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} / 4096) \n    / \n    (aerospike_namespace_partition_tree_sprigs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n)",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Used % vs High Water Mark % ",
     "type": "timeseries",
     "description": "Represents how much used memory is consumed against the High Water Memory configured, the lower it is the better,\nNOTE: no data will be shown if High Water Pct is not configured.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(((aerospike_namespace_index_flash_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})\n/ on ( job, clusrer_name, service, ns)\naerospike_namespace_index_type_mounts_high_water_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"} !=0)*100\n)",
       "legendFormat": "{{service}}/{{ns}}"
      },
      {
       "expr": "(((aerospike_namespace_index_mounts_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})\n/ on ( job, clusrer_name, service, ns)\naerospike_namespace_index_type_evict_mounts_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"} !=0)*100\n)",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "% Index  - alloc, used ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_namespace_index_flash_alloc_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : Allocated"
      },
      {
       "expr": "aerospike_namespace_index_flash_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      },
      {
       "expr": "aerospike_namespace_index_mounts_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      }
     ]
    },
    {
     "title": "Bytes - alloc, used",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : Allocated"
      },
      {
       "expr": "aerospike_namespace_index_flash_used_bytes{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      },
      {
       "expr": "aerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources - Sindex - $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Data % vs High Water Mark %",
     "type": "timeseries",
     "description": "Represents how much used memory is consumed against the High Water Memory configured, the lower it is the better",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(((aerospike_namespace_sindex_flash_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})\n/ on (job, cluster, service, ns) \naerospike_namespace_index_type_mounts_high_water_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"} !=0)*100\n)",
       "legendFormat": "{{service}}/{{ns}}"
      },
      {
       "expr": "(((aerospike_namespace_sindex_mounts_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})\n/ on (job, cluster, service, ns) \naerospike_namespace_index_type_evict_mounts_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"} !=0)*100\n)",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Bytes -  used ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_sindex_flash_used_bytes{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      },
      {
       "expr": "aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      }
     ]
    },
    {
     "title": "% SIndex  - used ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_namespace_sindex_flash_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      },
      {
       "expr": "aerospike_namespace_sindex_mounts_used_pct{job=\"$job_name\", cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources - Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Data - used, available (topk)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($topk_limit, 100 - aerospike_namespace_device_free_pct{cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "{{service}}/{{ns}} - Device Used"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_device_available_pct {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} )",
       "legendFormat": "{{service}}/{{ns}} - Device Available"
      },
      {
       "expr": "topk($topk_limit,100 - aerospike_namespace_pmem_free_pct {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} - Pmem Used"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_pmem_available_pct {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} )",
       "legendFormat": "{{service}}/{{ns}} - Pmem Available"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_data_used_pct {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} - Data Used"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_data_avail_pct {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"} )",
       "legendFormat": "{{service}}/{{ns}} - Data Available"
      }
     ]
    },
    {
     "title": "Latencie writes > $latency_time_bucket ms",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(\n    (aerospike_latencies_write_ms_bucket{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=\"+Inf\"})\n    - ignoring (le)\n    (aerospike_latencies_write_ms_bucket{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=\"$latency_time_bucket\"})\n)",
       "legendFormat": "{{service}}/{{ns}} - Write "
      }
     ]
    },
    {
     "title": "Defrag - Read and Writes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_namespace_storage_engine_file_defrag_reads{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - File Reads"
      },
      {
       "expr": "aerospike_namespace_storage_engine_device_defrag_reads{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} - Device Reads"
      },
      {
       "expr": "aerospike_namespace_storage_engine_file_defrag_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\nor\naerospike_namespace_storage_engine_device_defrag_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n",
       "legendFormat": "{{service}}/{{ns}} - Writes"
      },
      {
       "expr": "aerospike_namespace_storage_engine_device_defrag_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n",
       "legendFormat": "{{service}}/{{ns}} - Writes"
      }
     ]
    },
    {
     "title": "Defrag Q",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\naerospike_namespace_storage_engine_file_defrag_q{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\nor\naerospike_namespace_storage_engine_device_defrag_q{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "{{service}}/{{ns}} - Q"
      }
     ]
    },
    {
     "title": "NSUP - Cycle Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_nsup_cycle_duration{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Resources - OS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - system",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_node_stats_system_free_mem_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"} ",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Index Pressure - Memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_index_pressure_dirty_memory {job=\"$job_name\", cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace\"})",
       "legendFormat": "{{service}}/{{ns}} : Total"
      },
      {
       "expr": "(aerospike_namespace_index_pressure_total_memory {job=\"$job_name\", cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace\"})",
       "legendFormat": "{{service}}/{{ns}} : Dirty"
      }
     ]
    },
    {
     "title": "Index Age ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_namespace_index_type_mount_age {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace\"} ",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Sindex Age",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_namespace_sindex_type_mount_age {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace\"} ",
       "legendFormat": "{{ns}}"
      }
     ]
    }
   ]
  }
 ]
}