{
 "title": "Datacenter_Comparison v14",
 "description": "The datacenter comparison dashboard helps to visualise the differences between clusters by comparing various resources at cluster and namespace level.",
 "tags": [
  "Aerospike",
  "Datacenter Comparison"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "Job Names",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Clusters",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=~\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "versus_cluster",
    "label": "Compare with Clusters",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=~\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "versus_node",
    "label": "Versus_Node",
    "query": {
     "query": "label_values(aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$versus_cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=~\"$job_name\", cluster_name=~\"$cluster|$versus_cluster\", service=~\"$node|$versus_node\" },ns)"
    }
   },
   { "name": "DS_EXPRESSION", "query": "__expr__" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Cluster Name",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;background-color:rgb(55, 135, 45);font-size:50px\"><b>$cluster</b></p>"
   }
  },
  {
   "type": "text",
   "description": "Cluster Name",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\r\n<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:50px\"><b>$versus_cluster</b></p>\r\n"
   }
  },
  { "title": "Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "-- Basics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Size",
     "type": "stat",
     "description": "Cluster size",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "#sum(aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$cluster\"})\r\ncount_values (\"size\", (aerospike_node_stats_cluster_size{job=~\"$job_name\", cluster_name=~\"$cluster\"}) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporters",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count(aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$cluster\"}))",
       "legendFormat": "Aerospike Exporters"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "stat",
     "description": "Cluster size",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "#sum(aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$cluster\"})\r\ncount_values (\"size\", (aerospike_node_stats_cluster_size{job=~\"$job_name\", cluster_name=~\"$versus_cluster\"}) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporters",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count (aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$versus_cluster\"}))",
       "legendFormat": "Aerospike Exporters"
      }
     ]
    },
    {
     "title": "Aerospike Version",
     "type": "stat",
     "description": "Build version",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (build) (aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
       "legendFormat": "{{build}}"
      }
     ]
    },
    {
     "title": "Aerospike Version",
     "type": "stat",
     "description": "Build version",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (build) (aerospike_node_up{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\"})",
       "legendFormat": "{{build}}"
      }
     ]
    },
    {
     "title": "Connections (total)",
     "type": "stat",
     "description": "Client connection count",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_node_stats_client_connections{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Client"
      },
      {
       "expr": "sum(aerospike_node_stats_fabric_connections{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Fabric"
      },
      {
       "expr": "sum(aerospike_node_stats_heartbeat_connections{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Heartbeat"
      }
     ]
    },
    {
     "title": "Connections (total)",
     "type": "stat",
     "description": "Client connection count",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_node_stats_client_connections{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Client"
      },
      {
       "expr": "sum(aerospike_node_stats_fabric_connections{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Fabric"
      },
      {
       "expr": "sum(aerospike_node_stats_heartbeat_connections{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Heartbeat"
      }
     ]
    }
   ]
  },
  { "title": "-- Unique Data Usage (Bytes) ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$cluster",
   "type": "stat",
   "description": "Display Unique Data Utilization across all  namespaces",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($6_Q_USAGE_BYTE + $7_Q_USAGE_BYTE) * $QR_RULE_CAN_SHOW",
     "type": "math"
    }
   ]
  },
  {
   "title": "$versus_cluster",
   "type": "stat",
   "description": "Display Unique Data Utilization across all  namespaces",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "repeat": "versus_cluster",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($6_Q_USAGE_BYTE + $7_Q_USAGE_BYTE) * $QR_RULE_CAN_SHOW",
     "type": "math"
    }
   ]
  },
  {
   "title": "-- Resources - CPU & Memory ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    { "title": "% CPU usage (avg)", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
    {
     "title": "$cluster",
     "type": "stat",
     "description": "Percentage of CPU usage",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
     "repeat": "cluster",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(aerospike_node_stats_process_cpu_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "ASD"
      },
      {
       "expr": "avg (aerospike_node_stats_system_total_cpu_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$versus_cluster",
     "type": "stat",
     "description": "Percentage of CPU usage",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
     "repeat": "versus_cluster",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (aerospike_node_stats_process_cpu_pct{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "ASD "
      },
      {
       "expr": "avg (aerospike_node_stats_system_total_cpu_pct{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total"
      }
     ]
    },
    { "title": "Memory & Heap (avg)", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
    {
     "title": "$cluster",
     "type": "stat",
     "description": "\n",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
     "repeat": "cluster",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(aerospike_node_stats_heap_efficiency_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Heap Efficiency"
      },
      {
       "expr": "avg(aerospike_node_stats_heap_active_kbytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Active Heap"
      },
      {
       "expr": "avg(aerospike_node_stats_heap_mapped_kbytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Mapped"
      },
      {
       "expr": "avg(aerospike_node_stats_heap_allocated_kbytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Allocated Heap"
      },
      {
       "expr": "avg(aerospike_node_stats_system_free_mem_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Free System"
      }
     ]
    },
    {
     "title": "$versus_cluster",
     "type": "stat",
     "description": "\n",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
     "repeat": "versus_cluster",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(aerospike_node_stats_heap_efficiency_pct{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Heap Efficiency"
      },
      {
       "expr": "avg(aerospike_node_stats_heap_active_kbytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Active Heap"
      },
      {
       "expr": "avg(aerospike_node_stats_heap_mapped_kbytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Mapped"
      },
      {
       "expr": " avg(aerospike_node_stats_heap_allocated_kbytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Allocated Heap"
      },
      {
       "expr": "avg(aerospike_node_stats_system_free_mem_pct{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Free System"
      }
     ]
    }
   ]
  },
  {
   "title": "-- Client Throughput : Read & Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Reads (TPS) (total)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total reads = client_read_success + client_read_error + client_read_timeout + client_read_not_found + batch_sub_read_success + batch_sub_read_error + batch_sub_read_timeout + batch_sub_read_not_found\n2. Successful reads = client_read_success + batch_sub_read_success\n3. Errored reads = client_read_error + batch_sub_read_error\n4. Timedout reads = client_read_timeout + batch_sub_read_timeout\n5. Not found = client_read_not_found + batch_sub_not_found",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": " Successful"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": " Error"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Timeout"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "NotFound"
      }
     ]
    },
    {
     "title": "Client Reads (TPS) (total)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total reads = client_read_success + client_read_error + client_read_timeout + client_read_not_found + batch_sub_read_success + batch_sub_read_error + batch_sub_read_timeout + batch_sub_read_not_found\n2. Successful reads = client_read_success + batch_sub_read_success\n3. Errored reads = client_read_error + batch_sub_read_error\n4. Timedout reads = client_read_timeout + batch_sub_read_timeout\n5. Not found = client_read_not_found + batch_sub_not_found",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_read_not_found{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_not_found{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Successful"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Error"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Timeout"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_read_not_found{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_read_not_found{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "NotFound"
      }
     ]
    },
    {
     "title": "Client Writes (TPS) (total)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total writes = client_write_success + client_write_error + client_write_timeout + batch_sub_write_success + batch_sub_write_error + batch_sub_write_timeout\n2. Successful writes = client_write_success + batch_sub_write_success\n3. Errored writes = client_write_error + batch_sub_write_error\n4. Timedout writes = client_write_timeout + batch_sub_write_timeout",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(aerospike_namespace_client_write_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_write_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Successful"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Error"
      },
      {
       "expr": "sum  (rate(aerospike_namespace_client_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Timeout"
      }
     ]
    },
    {
     "title": "Client Writes (TPS) (total)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total writes = client_write_success + client_write_error + client_write_timeout + batch_sub_write_success + batch_sub_write_error + batch_sub_write_timeout\n2. Successful writes = client_write_success + batch_sub_write_success\n3. Errored writes = client_write_error + batch_sub_write_error\n4. Timedout writes = client_write_timeout + batch_sub_write_timeout",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (rate(aerospike_namespace_client_write_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_write_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m])+rate(aerospike_namespace_client_write_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_write_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_success{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Successful"
      },
      {
       "expr": "sum  (rate(aerospike_namespace_client_write_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_error{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Error"
      },
      {
       "expr": "sum (rate(aerospike_namespace_client_write_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]) + rate(aerospike_namespace_batch_sub_write_timeout{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}[1m]))",
       "legendFormat": "Timeout"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  { "title": "Namespaces Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "-- Basics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace Count",
     "type": "stat",
     "description": "Namespaces",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count (aerospike_namespace_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"} ))",
       "legendFormat": "Namespaces count"
      }
     ]
    },
    {
     "title": "Strong consistency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values by (sc) (\"sc\",aerospike_namespace_strong_consistency{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespace Count",
     "type": "stat",
     "description": "Namespaces",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(count (aerospike_namespace_objects{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\"} ))",
       "legendFormat": "Namespaces Count"
      }
     ]
    },
    {
     "title": "Strong consistency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values by (sc) (\"sc\",aerospike_namespace_strong_consistency{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Partitions (total)",
     "type": "stat",
     "description": "Namespace dead or unavailable partitions",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_dead_partitions{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Dead : "
      },
      {
       "expr": "sum(aerospike_namespace_unavailable_partitions{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Unavailable : "
      }
     ]
    },
    {
     "title": "Partitions (total)",
     "type": "stat",
     "description": "Namespace dead or unavailable partitions",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_dead_partitions{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Dead : "
      },
      {
       "expr": "sum(aerospike_namespace_unavailable_partitions{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Unavailable : "
      }
     ]
    }
   ]
  },
  {
   "title": "-- Migrations, Objects : $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Effective Replication factor (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  (aerospike_namespace_effective_replication_factor{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (ns,cluster_name)",
       "legendFormat": "{{cluster_name}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Truncating (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_truncating{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) by (ns,cluster_name) >0",
       "legendFormat": "{{cluster_name}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Effective Replication factor (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_effective_replication_factor{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}) by (ns,cluster_name)",
       "legendFormat": "{{cluster_name}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Truncating (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_truncating{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})  by (ns, cluster_name) >0",
       "legendFormat": "{{cluster_name}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Migrations (total)",
     "type": "stat",
     "description": "Displays sum of partitions Remaining and Active which are Received or Transmitted across selected cluster for the selected nodes and namespaces",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_migrate_rx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_rx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": "RX Remaining"
      },
      {
       "expr": "sum (aerospike_namespace_migrate_rx_partitions_active{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": "RX Active "
      },
      {
       "expr": "sum (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": " TX Remaining"
      },
      {
       "expr": "sum (aerospike_namespace_migrate_tx_partitions_active{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": " TX Active"
      }
     ]
    },
    {
     "title": "Migrations (total)",
     "type": "stat",
     "description": "Displays sum of partitions Remaining and Active which are Received or Transmitted across selected cluster for the selected nodes and namespaces",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_migrate_rx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_rx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": "RX Remaining"
      },
      {
       "expr": "sum (aerospike_namespace_migrate_rx_partitions_active{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": "RX Active "
      },
      {
       "expr": "sum (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": " TX Remaining"
      },
      {
       "expr": "sum (aerospike_namespace_migrate_tx_partitions_active{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": " TX Active"
      }
     ]
    },
    {
     "title": "Objects",
     "type": "stat",
     "description": "Namespace prole objects",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "legendFormat": "Prole objects" }
     ]
    },
    {
     "title": "Master (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_master_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Master objects"
      }
     ]
    },
    {
     "title": "Evicted (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_evicted_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Evicted Objects"
      }
     ]
    },
    {
     "title": "Prole (total)",
     "type": "stat",
     "description": "Namespace prole objects",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_prole_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})  ",
       "legendFormat": "Prole objects"
      }
     ]
    },
    {
     "title": "Master (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_master_objects{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Master objects"
      }
     ]
    },
    {
     "title": "Evicted (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_evicted_objects{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Evicted objects "
      }
     ]
    },
    {
     "title": "Prole (total)",
     "type": "stat",
     "description": "Namespace prole objects",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_prole_objects{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})  ",
       "legendFormat": "Prole objects"
      }
     ]
    },
    {
     "title": "Expired (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_expired_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Expired Objects"
      }
     ]
    },
    {
     "title": "Tombstones (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_tombstones{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Tombstones objects "
      }
     ]
    },
    {
     "title": "Non-Replica (total)",
     "type": "stat",
     "description": "Namespace non-replica objects",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_non_replica_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "Non-Replica objects"
      }
     ]
    },
    {
     "title": "Expired (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_expired_objects{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Expired objects"
      }
     ]
    },
    {
     "title": "Tombstones (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_tombstones{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Tombstones objects "
      }
     ]
    },
    {
     "title": "Non-Replica (total)",
     "type": "stat",
     "description": "Namespace non-replica objects",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_non_replica_objects{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "Non-Replica objects"
      }
     ]
    },
    {
     "title": "XDR Tombstones (total)",
     "type": "stat",
     "description": "Number of tombstones which are created by XDR for non-durable client deletes. This includes both master and prole.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_xdr_tombstones{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "XDR Tombstones"
      }
     ]
    },
    {
     "title": "XDR Bin Cemeteries (total)",
     "type": "stat",
     "description": "Number of tombstones with bin-tombstones. They are generated when bin convergence is enabled and a record is durably deleted.",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_xdr_bin_cemeteries{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "XDR Bin Cemeteries"
      }
     ]
    },
    {
     "title": "XDR Tombstones (total)",
     "type": "stat",
     "description": "Number of tombstones which are created by XDR for non-durable client deletes. This includes both master and prole.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_xdr_tombstones{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "XDR Tombstones"
      }
     ]
    },
    {
     "title": "XDR Bin Cemeteries (total)",
     "type": "stat",
     "description": "Number of tombstones with bin-tombstones. They are generated when bin convergence is enabled and a record is durably deleted.",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_xdr_bin_cemeteries{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "XDR Bin Cemeteries"
      }
     ]
    }
   ]
  },
  {
   "title": "-- Memory, Data & Index : $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Data Total, Used & Free : $namespace",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
    },
    {
     "title": "Data bytes",
     "type": "stat",
     "description": "Displays sum of all device or memory sum of allocated bytes",
     "gridPos": { "h": 3, "w": 8, "x": 2, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total : "
      },
      {
       "expr": "avg(aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg : "
      }
     ]
    },
    {
     "title": "Data bytes",
     "type": "stat",
     "description": "Displays sum of all device or memory sum of allocated bytes",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total : "
      },
      {
       "expr": "avg (aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg : "
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Displays sum of all device or memory used by data (without index) ",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Free ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} - aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} - aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Displays sum of all device or memory used by data (without index) ",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Free",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"} - aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (aerospike_namespace_data_total_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"} - aerospike_namespace_data_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Index Used & Alloc : $namespace",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
     "options": { "content": " " }
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Displays sum of all device or memory used by index, sindex and set-index",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (\r\naerospike_namespace_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_sindex_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_set_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\r\n)",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (\r\naerospike_namespace_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_sindex_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_set_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\r\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "(Flash) alloc",
     "type": "stat",
     "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_index_flash_alloc_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_index_flash_alloc_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Displays sum of all device or memory used by index, sindex and set-index",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (\r\naerospike_namespace_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_sindex_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_set_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}\r\n)",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (\r\naerospike_namespace_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_sindex_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}\r\nor\r\naerospike_namespace_set_index_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"}\r\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "(Flash) alloc ",
     "type": "stat",
     "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_index_flash_alloc_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_index_flash_alloc_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Device  (6.x deprecated)  Used & Free : $namespace",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
     "options": { "content": " " }
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Namespace storage usage in bytes,\nSum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Free",
     "type": "stat",
     "description": "Namespace storage free bytes,\nSum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_device_total_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (aerospike_namespace_device_total_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Namespace storage usage in bytes, Sum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Free",
     "type": "stat",
     "description": "Namespace storage free bytes, Sum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_device_total_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (aerospike_namespace_device_total_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_device_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Memory (6.x deprecated) Total, Used & Free: $namespace",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
     "options": { "content": " " }
    },
    {
     "title": "Total",
     "type": "stat",
     "description": "$cluster - total memory (memory_size) in bytes, Sum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg (aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Namespace storage usage in bytes \nSum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Free ",
     "type": "stat",
     "description": "$cluster - free memory ((memory_free_pct / 100) * memory_size) in bytes, Sum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Total ",
     "type": "stat",
     "description": "$cluster - total memory (memory_size) in bytes, Sum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "description": "Total $cluster memory used,\nSum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Free",
     "type": "stat",
     "description": "$versus_cluster - free memory ((memory_free_pct / 100) * memory_size) in bytes, Sum&Avg of all the nodes under the $cluster cluster",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sum"
      },
      {
       "expr": "avg(aerospike_namespace_memory_size{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_memory_used_bytes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    { "title": "...", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "options": { "content": " " } },
    {
     "title": "Stop Writes / HWM breached (total)",
     "type": "stat",
     "description": "Displays sum of namespace stop_writes, clock skew stop writes and high water mark breached flags across all the nodes and namespaces in selected cluster, a positive value means some issue with resource utilization or configurations ",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_stop_writes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Stop Writes"
      },
      {
       "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Clock Skew Stop Writes"
      },
      {
       "expr": "sum(aerospike_namespace_hwm_breached{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "HWM Breached"
      }
     ]
    },
    {
     "title": "Stop Writes / HWM breached (total)",
     "type": "stat",
     "description": "Displays sum of namespace stop_writes, clock skew stop writes and high water mark breached flags across all the nodes and namespaces in selected cluster, a positive value means some issue with resource utilization or configurations ",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_stop_writes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Stop Writes"
      },
      {
       "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Clock Skew Stop Writes"
      },
      {
       "expr": "sum(aerospike_namespace_hwm_breached{job=~\"$job_name\", cluster_name=~\"$versus_cluster\", service=~\"$versus_node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "HWM Breached"
      }
     ]
    }
   ]
  }
 ]
}