{
 "title": "MRT View",
 "description": "This dashboard helps to track Aerospike transaction metrics, including success rates, errors, and rollbacks.",
 "tags": [
  "monitoring",
  "mrt",
  "usecase"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_namespace_mrt_roll_forward_success, job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\"},ns)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success (total) (rate)",
   "type": "stat",
   "description": "Displays the total success rate of MRT roll forward, roll back, monitor roll forward, monitor roll back, and verify read.",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\",}[$__rate_interval]))",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(rate(aerospike_namespace_mrt_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Rollback"
    },
    {
     "expr": "sum(\n    rate(aerospike_namespace_mrt_monitor_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "Monitor Commit"
    },
    {
     "expr": "sum(rate(aerospike_namespace_mrt_monitor_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Monitor Rollback"
    },
    {
     "expr": "sum(rate(aerospike_namespace_mrt_verify_read_success{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Verify Read"
    }
   ]
  },
  {
   "title": "Error/Timeout - (total) (rate)",
   "type": "stat",
   "description": "Displays the total error and timout rate of MRT roll forward, roll back, monitor roll forward, monitor roll back, and verify read.",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    rate(aerospike_namespace_mrt_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_verify_read_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n)\n\n\n",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(\n    rate(aerospike_namespace_mrt_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_verify_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])\n)\n\n    ",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Monitors Active (total)",
   "type": "stat",
   "description": "Displays the total number of transactions currently being driven by a monitor.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_mrt_monitors_active{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Active Monitors"
    }
   ]
  },
  {
   "title": "Provisionals (total)",
   "type": "stat",
   "description": "Displays the total number of provisional records.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_mrt_provisionals{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Provisionals"
    }
   ]
  },
  { "title": "Monitor Set Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Data Used (bytes)",
   "type": "stat",
   "description": "Device storage used by this set in bytes, for the data part (does not include index part).",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"<ERO~MRT\"} )\n",
     "legendFormat": "Success (rate)"
    }
   ]
  },
  {
   "title": "Objects (Ongoing MRTs)",
   "type": "stat",
   "description": "Total number of objects (master and all replicas) in this set on this node.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"<ERO~MRT\"} )",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "title": "Tombstones (total)",
   "type": "stat",
   "description": "Total number of tombstones (master and all replicas) in this set on this node.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sets_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"<ERO~MRT\"} )",
     "legendFormat": "Tombstones Count"
    }
   ]
  },
  {
   "title": "Stop Writes Size (Unique values)",
   "type": "stat",
   "description": "More details about [stop writes size](https://docs.aerospike.com/reference/configuration#stop-writes-size).",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"stop_write_size\", aerospike_sets_stop_writes_size{job=\"$job_name\", cluster_name=~\"$cluster|$^\", ns=~\"$namespace\", set=~\"<ERO~MRT\",} or on() vector(-1))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Stop Writes Count (Unique values)",
   "type": "stat",
   "description": "More details about [stop writes count](https://docs.aerospike.com/reference/configuration#stop-writes-count).",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"stop_write_cnt\",aerospike_sets_stop_writes_count{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}>0)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Data Used (bytes)",
   "type": "timeseries",
   "description": "Device storage used by this set in bytes, for the data part (does not include index part).",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"<ERO~MRT\"} )\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Objects (Ongoing MRTs)",
   "type": "timeseries",
   "description": "Total number of objects (master and all replicas) in this set on this node.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", set=~\"<ERO~MRT\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Success (total) (rate)",
     "type": "stat",
     "description": "Displays the success rate of MRT roll forward, roll back, monitor roll forward, monitor roll back, and verify read.",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "Commit"
      },
      {
       "expr": "sum(rate(aerospike_namespace_mrt_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "Rollback"
      },
      {
       "expr": "sum(\n    rate(aerospike_namespace_mrt_monitor_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "Monitor Commit"
      },
      {
       "expr": "sum(rate(aerospike_namespace_mrt_monitor_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "Monitor Rollback"
      },
      {
       "expr": "sum(rate(aerospike_namespace_mrt_verify_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "Verify Read"
      }
     ]
    },
    {
     "title": "Error/Timeout (rate)",
     "type": "stat",
     "description": "Displays the error and timout rate of MRT roll forward, roll back, monitor roll forward, monitor roll back, and verify read.",
     "gridPos": { "h": 4, "w": 5, "x": 13, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    rate(aerospike_namespace_mrt_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_verify_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)\n\n\n",
       "legendFormat": "Error"
      },
      {
       "expr": "sum(\n    rate(aerospike_namespace_mrt_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_verify_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n+\n    rate(aerospike_namespace_mrt_monitor_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)\n\n    ",
       "legendFormat": "Timeout"
      }
     ]
    },
    {
     "title": "Monitors Active (total)",
     "type": "stat",
     "description": "Displays the number of transactions currently being driven by a monitor.",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_mrt_monitors_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Active Monitors"
      }
     ]
    },
    {
     "title": "Provisionals (total)",
     "type": "stat",
     "description": "Displays the number of provisional records.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_mrt_provisionals{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Provisionals"
      }
     ]
    },
    {
     "title": "Commit (total) (rate)",
     "type": "timeseries",
     "description": "Number of roll forward transactions that succeeded,failed and timeout.\n",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Success"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Error"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Timeout"
      }
     ]
    },
    {
     "title": "Rollback (total) (rate)",
     "type": "timeseries",
     "description": "Number of roll back transactions that succeeded,failed and timed out.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Success"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Error"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Timeout"
      }
     ]
    },
    {
     "title": "Monitor Commit (total) (rate)",
     "type": "timeseries",
     "description": "Subset of mrt_roll_forward_success,error and timeout where the monitor did the roll forward.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Success"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Error"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Timeout"
      }
     ]
    },
    {
     "title": "Monitor Rollback (total) (rate)",
     "type": "timeseries",
     "description": "Subset of mrt_roll_back_success,error and timeout where the monitor did the rollback.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Success"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Error"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Timeout"
      }
     ]
    },
    {
     "title": "Verify Read (total) (rate)",
     "type": "timeseries",
     "description": "Number of verify read transactions that succeeded,failed and timed out.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_verify_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Success"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_verify_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Error"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_verify_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Timeout"
      }
     ]
    },
    {
     "title": "Error (total) (rate)",
     "type": "timeseries",
     "description": "Displays the total error and timout rate of MRT roll forward, roll back, monitor roll forward, monitor roll back, and verify read.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Forward"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Rollback"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_verify_read_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Verify Read"
      },
      {
       "expr": "sum by (ns)(rate(aerospike_namespace_mrt_monitor_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))\n\n\n",
       "legendFormat": "{{ns}}: Roll Forward"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Monitor Rollback"
      }
     ]
    },
    {
     "title": "Timeout (total) (rate)",
     "type": "timeseries",
     "description": "Displays the total error and timout rate of MRT roll forward, roll back, monitor roll forward, monitor roll back, and verify read.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Roll Forward"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Rollback"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_verify_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Verify Read"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Monitor Roll Forward"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}: Monitor Rollback"
      }
     ]
    },
    {
     "title": "Blocked / Mistmatch (total) (rate)",
     "type": "timeseries",
     "description": "Number of transactions or read/write commands blocked or mismatches by an ongoing transaction",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_fail_mrt_blocked{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Blocked",
       "legendFormatFormat": "{{ns}}:Blocked"
      },
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_fail_mrt_version_mismatch{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}} : Version Mismatch"
      }
     ]
    },
    {
     "title": "Monitors Active ",
     "type": "timeseries",
     "description": "Number of transactions currently being driven by a monitor.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "(aerospike_namespace_mrt_monitors_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Monitor Tombstone Creates (total) (rate)",
     "type": "timeseries",
     "description": "Number of times monitor rolls (forward or back) generate tombstones from nothing.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_mrt_monitor_roll_tombstone_creates{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Provisionals",
     "type": "timeseries",
     "description": "Number of provisional records.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "(aerospike_namespace_mrt_provisionals{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{ns}}"
      }
     ]
    }
   ]
  }
 ]
}