{
 "title": "Aerospike Node & Host view",
 "description": "Host & Aerospike Node Dashboard helps to analyse and fix errors by comparing performance of key aerospike metrics with relevant host metrics",
 "tags": [
  "usecases",
  "node",
  "host"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values({__name__=~\"aerospike_node_stats_uptime|node_uname_info\"},job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"aerospike_node_stats_uptime|node_uname_info\", job=~\"$job_name\"}, cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node/Host",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=~\"$job_name\", cluster_name=~\"$cluster\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\" },ns)"
    }
   },
   { "name": "latencytimeunit", "label": "Latency Time Unit", "query": { "query": "metrics(aerospike_latencies_)" } },
   {
    "name": "dc",
    "label": "XDR-DC",
    "query": {
     "query": "label_values(aerospike_xdr_lap_us{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|.*\" },dc)"
    }
   },
   { "name": "topk_limit", "label": "Top-K", "query": "10" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<b>Note: this dashboard requires Node-Exporter deployed in the same host where the aerospike server and aerospike-prometheus-exporter are running. \n<br/>If aerospike-prometheus-exporter and node-exporter are running as different jobs in prometheus.yml configuration, user need to select both the jobs to see the data.\n</b>"
   }
  },
  {
   "title": "Latencies, Reads, Writes ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Reads (TPS) (TopK)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total reads = client_read_success + client_read_error + client_read_timeout + client_read_not_found + batch_sub_read_success + batch_sub_read_error + batch_sub_read_timeout + batch_sub_read_not_found\n2. Successful reads = client_read_success + batch_sub_read_success\n3. Errored reads = client_read_error + batch_sub_read_error\n4. Timedout reads = client_read_timeout + batch_sub_read_timeout\n5. Not found = client_read_not_found + batch_sub_not_found",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk_limit, (rate(aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) ) )",
       "legendFormat": "{{service}}/{{ns}}: Total"
      },
      {
       "expr": "topk($topk_limit, (rate(aerospike_namespace_client_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])))",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "topk($topk_limit, (rate(aerospike_namespace_client_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])))",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      },
      {
       "expr": "topk($topk_limit, ( rate(aerospike_namespace_client_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_not_found{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) ))",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      }
     ]
    },
    {
     "title": "Client Writes (TPS) (TopK)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total writes = client_write_success + client_write_error + client_write_timeout + batch_sub_write_success + batch_sub_write_error + batch_sub_write_timeout\n2. Successful writes = client_write_success + batch_sub_write_success\n3. Errored writes = client_write_error + batch_sub_write_error\n4. Timedout writes = client_write_timeout + batch_sub_write_timeout",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk_limit, (rate(aerospike_namespace_client_write_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) ))",
       "legendFormat": "{{service}}/{{ns}}: Total"
      },
      {
       "expr": "topk($topk_limit, (rate(aerospike_namespace_client_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])))",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      },
      {
       "expr": "topk($topk_limit, (rate(aerospike_namespace_client_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}[$__rate_interval])))",
       "legendFormat": "{{service}}/{{ns}}: Error"
      }
     ]
    },
    {
     "title": "Connections Opened / Closed (TopK)",
     "type": "timeseries",
     "description": "Rate of client, heartbeat and fabric connections opened or closed",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk_limit, (rate(aerospike_node_stats_client_connections_opened{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "{{service}} Opened"
      },
      {
       "expr": "topk($topk_limit, (rate(aerospike_node_stats_client_connections_closed{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "{{service}} Closed"
      }
     ]
    },
    {
     "title": "Latency: Reads / ms",
     "type": "timeseries",
     "description": "Reads per second",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(aerospike_latencies_read_${latencytimeunit}_bucket{job=~\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\", le=~\"[4]*\"}) by (le, service)",
       "legendFormat": "{{service}} <={{le}}${latencytimeunit}"
      },
      {
       "expr": "avg by (service)(aerospike_latencies_read_${latencytimeunit}_count{job=~\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}} Ops/sec"
      }
     ]
    },
    {
     "title": "Latency: Writes / ms",
     "type": "timeseries",
     "description": "Writes per second",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(le, service) (aerospike_latencies_write_${latencytimeunit}_bucket{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\", le=~\"[4]*\"})",
       "legendFormat": "{{service}} <={{le}}${latencytimeunit}"
      },
      {
       "expr": "avg by (service) (aerospike_latencies_write_${latencytimeunit}_count{job=~\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}} Ops/sec"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Percentage of CPU usage by the asd process.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_node_stats_process_cpu_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} - ASD"
      },
      {
       "expr": "aerospike_node_stats_system_total_cpu_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} - Host"
      }
     ]
    },
    {
     "title": "Host Disk Read/Write Latency (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk($topk_limit, (rate(node_disk_write_time_seconds_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) and rate(node_disk_writes_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) > 0))",
       "legendFormat": "{{instance}}/{{device}} - Write"
      },
      {
       "expr": "topk($topk_limit, (rate(node_disk_read_time_seconds_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])  and rate(node_disk_reads_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) > 0 ))",
       "legendFormat": "{{instance}}/{{device}} - Read"
      }
     ]
    },
    {
     "title": "Host Disk Read / Write (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($topk_limit, (rate(node_disk_written_bytes_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} / {{device}} - Write"
      },
      {
       "expr": "topk($topk_limit, (rate(node_disk_read_bytes_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} / {{device}} - Read"
      }
     ]
    },
    {
     "title": "Host Disk Space Filling up (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance, device)(rate(node_filesystem_avail_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) * 100 / node_filesystem_size_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\"})",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Host Network Transmit / Receive Errors (Rate) (TopK)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk ($topk_limit, (rate(node_network_receive_errs_total{cluster_name=~\"$cluster\", job=~\"$job_name\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{device}} - Receive"
      },
      {
       "expr": "topk ($topk_limit, (rate(node_network_transmit_errs_total{cluster_name=~\"$cluster\", job=~\"$job_name\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Drop (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Host Network Traffic - retransmit (packets) (total) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_netstat_Tcp_RetransSegs{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval] ))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Host Memory Page Faults (Rate) ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_vmstat_pgfault{job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} Pgfault"
      },
      {
       "expr": "rate(node_vmstat_pgmajfault{job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} PgMajFault"
      },
      {
       "expr": "rate(node_vmstat_pgfault{job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])  - rate(node_vmstat_pgmajfault{job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} PgMinFault"
      }
     ]
    },
    {
     "title": "Host Memory Filling up (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rate(node_memory_MemAvailable_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) / node_memory_MemTotal_bytes{job=~\"$job_name\", cluster_name=~\"$cluster\"} * 100 )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}",
       "legendFormat": "Max "
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}",
       "legendFormat": "Open files"
      }
     ]
    }
   ]
  },
  {
   "title": "Migrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Migrations (Partitions)",
     "type": "timeseries",
     "description": "Migrations remaining migrate_tx_partitions_remaining (transmit), migrate_rx_partitions_remaining (receive)",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_migrate_rx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} : Incoming "
      },
      {
       "expr": " (aerospike_namespace_migrate_tx_partitions_remaining{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} : Outgoing "
      },
      {
       "expr": " (aerospike_namespace_migrate_rx_partitions_active{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} : RX Active"
      },
      {
       "expr": "(aerospike_namespace_migrate_tx_partitions_active{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} : TX Active "
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Percentage of CPU usage by the asd process.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_node_stats_process_cpu_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} - ASD"
      },
      {
       "expr": "aerospike_node_stats_system_total_cpu_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} - Host"
      }
     ]
    },
    {
     "title": "Host Network Transmit & Receive Errors (Rate) (TopK)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk ($topk_limit, (rate(node_network_receive_errs_total{cluster_name=~\"$cluster\", job=~\"$job_name\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{device}} - Receive"
      },
      {
       "expr": "topk ($topk_limit, (rate(node_network_transmit_errs_total{cluster_name=~\"$cluster\", job=~\"$job_name\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Host Network Traffic - retransmit (packets) (total) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum (irate(node_netstat_Tcp_RetransSegs{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval] ))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic Drop (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Host Disk Read/Write Latency (Rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval])  and rate(node_disk_reads_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) > 0",
       "legendFormat": "{{instance}}/{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) and rate(node_disk_writes_completed_total{job=~\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]) > 0",
       "legendFormat": "{{instance}}/{{device}} - Write"
      }
     ]
    }
   ]
  },
  {
   "title": "XDR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "XDR Lag (TopK)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": " topk($topk_limit, ((rate(aerospike_xdr_lag{job=~\"$job_name\", cluster_name=~\"$cluster\",service=~\"$node.*\",ns=~\"$namespace|$^\"}[$__rate_interval]))))",
       "legendFormat": "{{service}} - Lag"
      }
     ]
    },
    {
     "title": "Retry Connection Reset (rate) (TopK)",
     "type": "timeseries",
     "description": "Number of retries due to connection reset and recoveries pending",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk_limit, (rate(aerospike_xdr_retry_conn_reset{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\", dc=~\"$dc|$^\"}[$__rate_interval])))",
       "legendFormat": "Reset {{service}} // {{dc}}"
      }
     ]
    },
    {
     "title": "XDR Latency ms",
     "type": "timeseries",
     "description": "Average network latency for the successfully shipped records",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_latency_ms{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node.*\"}",
       "legendFormat": " {{service}} // {{dc}}"
      }
     ]
    },
    {
     "title": "Host Network Traffic Drop (packets) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - {{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance }} - {{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Host Network Traffic - retransmit (packets) (total) (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_netstat_Tcp_RetransSegs{instance=~\"$node.*\",job=~\"$job_name\",cluster_name=~\"$cluster\"}[$__rate_interval] ))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Host Network Transmit & Receive Errors (Rate) (TopK)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk ($topk_limit, (rate(node_network_receive_errs_total{cluster_name=~\"$cluster\", job=~\"$job_name\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{device}} - Receive"
      },
      {
       "expr": "topk ($topk_limit, (rate(node_network_transmit_errs_total{cluster_name=~\"$cluster\", job=~\"$job_name\"}[$__rate_interval])))",
       "legendFormat": "{{instance}} {{device}} - Transmit"
      }
     ]
    }
   ]
  }
 ]
}