{
 "title": "Aerospike LRU Cache View",
 "description": "a usecase dashboard, to view various key metrics useful while using aerospike as a distributed cache,  dashboard displays key metrics like read_success, errors, timeouts etc.,",
 "tags": [
  "aerospike",
  "monitoring",
  "read",
  "usecase"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_namespace_read_touch_success,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_namespace_read_touch_success{job=~\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_namespace_read_touch_success{job=~\"$job_name\", cluster_name=~\"$cluster\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_read_touch_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\"},ns)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total (rate)",
   "type": "stat",
   "description": "Number of successful read touches,\nNumber of batch-index read subtransaction that failed with an error,\nNumber of batch-index read subtransaction that resulted in not found,\nNumber of batch-index read subtransactions that did not happen because the record was filtered out,\nNumber of batch-index read subtransactions that timed out.",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aerospike_namespace_read_touch_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(aerospike_namespace_read_touch_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))\n+\nsum(rate(aerospike_namespace_read_touch_tsvc_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(aerospike_namespace_read_touch_skip{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Skip"
    },
    {
     "expr": "sum(rate(aerospike_namespace_read_touch_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))\n+\nsum(rate(aerospike_namespace_read_touch_tsvc_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Ratio : Touch vs Reads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_read_touch_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}) / sum((aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"} != 0) + (aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"} !=0))",
     "legendFormat": "Read Ratio"
    }
   ]
  },
  {
   "title": "Objects (total)",
   "type": "stat",
   "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Master"
    },
    {
     "expr": "sum(aerospike_namespace_expired_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "title": "% TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "(aerospike_namespace_default_read_touch_ttl_pct{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}) ",
     "legendFormat": "{{service}}/{{ns}}"
    }
   ]
  },
  {
   "title": "Ratio : Touch vs Reads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "sum (aerospike_namespace_read_touch_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}) / sum((aerospike_namespace_batch_sub_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"} != 0) + (aerospike_namespace_client_read_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"} !=0))",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "Reads Success & Not Found (rate) (total)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in\n\n1. Touch successful reads = read_touch_success \n2. Regular/Batch successful reads = client_read_success + batch_sub_read_success\n3. Not found = client_read_not_found + batch_sub_not_found",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(aerospike_namespace_read_touch_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "Read Touch - Success"
    },
    {
     "expr": "sum (rate(aerospike_namespace_client_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "Read Client/Batch - Success"
    },
    {
     "expr": "sum (rate(aerospike_namespace_client_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "Read Client/Batch - Not Found"
    }
   ]
  },
  {
   "title": "Writes Success (rate) (total)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in\n\n1. Successful writes = client_write_success + batch_sub_write_success",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "Write Client/Batch - Success"
    }
   ]
  },
  {
   "title": "Touch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success (rate) (total)",
     "type": "timeseries",
     "description": "Number of successful read touches.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_read_touch_success{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Skip (rate) (total)",
     "type": "timeseries",
     "description": "Number of touches abandoned upon finding that another write (including an earlier touch) has taken place or is taking place, removing the need to proceed with the touch.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_read_touch_skip{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Error (rate) (total)",
     "type": "timeseries",
     "description": "Number of read touch errors which were not timeouts.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_read_touch_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Timeout (rate) (total)",
     "type": "timeseries",
     "description": "Number of touches that ended in timeout.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_read_touch_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "TSVC Error (rate) (total)",
     "type": "timeseries",
     "description": "Number of read touch subtransactions that failed with an error in the internal transaction queue. Does not include timeouts.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_read_touch_tsvc_error{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "TSVC Timeout (rate) (total)",
     "type": "timeseries",
     "description": "Number of read touches that time out early in the internal transaction queue, while waiting to be picked up by a service thread.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_read_touch_tsvc_timeout{job=~\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput (Read, Write)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Reads Error & Timeout (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Errored reads = client_read_error + batch_sub_read_error\n2. Timedout reads = client_read_timeout + batch_sub_read_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_client_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_client_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Client Writes Error & Timeout (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Errored writes = client_write_error + batch_sub_write_error\n2. Timedout writes = client_write_timeout + batch_sub_write_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Objects",
     "type": "timeseries",
     "description": "Namespace master objects",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Expired Objects",
     "type": "timeseries",
     "description": "Namespace expired objects",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_expired_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  }
 ]
}