{
 "title": "Rolling Restarts",
 "tags": [ "usecases" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   {
    "name": "latency_time_bucket",
    "label": "Latencies >",
    "query": "1,2,4,8,16,32,64,128,256,512,1024,2048,4096,16284,32768,65536"
   },
   { "name": "topk_limit", "label": "Top-K", "query": "15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "#\n<p>\n<b>Key metrics (<a href=\"https://docs.aerospike.com\" target=\"blank\"> Metrics Reference </a>) which needs to be monitored during a server activity, like 1. Restart, 2. Software upgrade, 3. Investigation etc.,\nData is shown as stats, error and resources, resource utilization is displayed for the TopK major consumers at a service and namespace level</b>\n</p>\n"
   }
  },
  {
   "title": "Aerospike Version",
   "type": "stat",
   "description": "Build version",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count_values by (build) (\"build_numbers\", (aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) )",
     "legendFormat": "{{build}}"
    }
   ]
  },
  {
   "title": "Cluster Size (Unique values)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count_values (\"size\", (aerospike_node_stats_cluster_size{cluster_name=\"$cluster\"}) )",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "HWM Breached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_hwm_breached {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "Migrations Remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (aerospike_namespace_migrate_rx_partitions_remaining{cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "RX"
    },
    {
     "expr": "sum (aerospike_namespace_migrate_tx_partitions_remaining{cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Quiesces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_effective_is_quiesced{ cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "Is Quiesced"
    },
    {
     "expr": "sum(aerospike_namespace_pending_quiesce{cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Stop Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ( aerospike_namespace_stop_writes {cluster_name=\"$cluster\", service=~\"$node|$^\"} )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_node_stats_client_connections{cluster_name=\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum ( aerospike_node_stats_fabric_connections {cluster_name=\"$cluster\",service=~\"$node|$^\"})",
     "legendFormat": "Fabric"
    },
    {
     "expr": "sum ( aerospike_node_stats_heartbeat_connections {cluster_name=\"$cluster\",service=~\"$node|$^\"})",
     "legendFormat": "Heartbeat"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum ((aerospike_namespace_unavailable_partitions{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}))",
     "legendFormat": "Unavailable"
    },
    {
     "expr": " sum ((aerospike_namespace_dead_partitions{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}))",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "Client Connections (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(aerospike_node_stats_client_connections_opened{ cluster_name=~\"$cluster\",service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} - Opened"
    },
    {
     "expr": "rate(aerospike_node_stats_client_connections_closed { cluster_name=~\"$cluster\",service=~\"$node|$^\"}[$__rate_interval])*-1",
     "legendFormat": "{{service}} - Closed"
    }
   ]
  },
  {
   "title": "Fabric Connections (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(aerospike_node_stats_fabric_connections_opened{ cluster_name=~\"$cluster\",service=~\"$node|$^\",}[$__rate_interval])   ",
     "legendFormat": "{{service}} - Opened"
    },
    {
     "expr": "rate(aerospike_node_stats_fabric_connections_closed { cluster_name=~\"$cluster\",service=~\"$node|$^\",}[$__rate_interval])*-1",
     "legendFormat": "{{service}} - Closed"
    }
   ]
  },
  {
   "title": "Heartbeat Connections (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(aerospike_node_stats_heartbeat_connections_opened{ cluster_name=~\"$cluster\",service=~\"$node|$^\",}[$__rate_interval])",
     "legendFormat": "{{service}} - Opened"
    },
    {
     "expr": "rate(aerospike_node_stats_heartbeat_connections_closed{ cluster_name=~\"$cluster\",service=~\"$node|$^\",}[$__rate_interval])*-1",
     "legendFormat": "{{service}} - Closed"
    }
   ]
  },
  {
   "title": "Quiesces",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (service) (aerospike_namespace_effective_is_quiesced{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Is Quiesced"
    },
    {
     "expr": "sum  by (service) (aerospike_namespace_pending_quiesce{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Pending Quiesce"
    }
   ]
  },
  {
   "title": "XDR Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": " (rate(aerospike_xdr_lag{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{service}} - Lag"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client - Read, Write, Delete, UDF (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_read_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_read_not_found{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Not Found"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_read_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_read_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Filtered Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_write_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Write Filtered Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_write_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Write Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_write_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Write Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_delete_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_delete_not_found{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Not Found"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_delete_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_delete_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Filtered Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_lang_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Lang Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_udf_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_udf_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_udf_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF Filtered Out"
      }
     ]
    },
    {
     "title": "Batch - Read, Write, Delete, UDF (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_read_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_read_not_found{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Not Found"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_read_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_read_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Read Filter Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_write_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Write Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_write_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Write Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_write_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Write Filter Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_delete_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_delete_not_found{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Not Found"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_delete_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Timeout"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_delete_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Delete Filtered Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_lang_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Lang Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_udf_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_udf_filtered_out{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF Filtered Out"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_udf_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF Timeout"
      }
     ]
    },
    {
     "title": "Incoming Proxy (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_read_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Read Error"
      },
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_read_filtered_out{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Read Filter Out"
      },
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_read_not_found{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Read Not Found"
      },
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_read_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Read Timeout"
      },
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_write_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Write Error"
      },
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_write_filtered_out{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Write Filtered Out"
      },
      {
       "expr": "sum by (service) (\nrate(aerospike_namespace_from_proxy_write_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Write Timeout"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_delete_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Delete Error"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_delete_filtered_out{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Delete Filtered Out"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_delete_not_found{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Delete Not Found"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_delete_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Delete Timeout"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_read_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Read"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_read_filtered_out{cluster_name=~\"$cluster\" ,service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Read Filtered Out"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_read_not_found{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Read Not Found"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_read_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Read Timeout"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_write_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Write Error"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_write_filtered_out{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Write Filter Out"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_write_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Write Timeout"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_delete_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Delete Error"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_delete_filtered_out{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Delete Filter Out"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_delete_not_found{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Delete Not Found"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_delete_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Delete Timeout"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_batch_sub_tsvc_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batc Sub TSVC Timeout"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_tsvc_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - TSVC Error"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_from_proxy_tsvc_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - TSVC Timeout"
      }
     ]
    },
    {
     "title": "Outgoing Proxy (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_client_proxy_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Client Timeout"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_client_proxy_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Client Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_batch_sub_proxy_timeout{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Timeout"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_batch_sub_proxy_error{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Batch Sub Error"
      }
     ]
    },
    {
     "title": "PI Query - Long, Short, Aggr, UDF (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_pi_query_long_basic_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"\n}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Long Basic Abort"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_pi_query_long_basic_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Long Basic Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_pi_query_short_basic_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Short Basic Timeout"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_pi_query_short_basic_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Short Basic Error"
      },
      {
       "expr": "sum by (service)( rate(aerospike_namespace_pi_query_aggr_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Aggr Error"
      },
      {
       "expr": "sum by (service)( \nrate(aerospike_namespace_pi_query_aggr_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Aggr Abort"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_pi_query_udf_bg_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF BG Abort"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_pi_query_udf_bg_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - UDF BG Error"
      },
      {
       "expr": "sum by (service)( rate(aerospike_namespace_pi_query_ops_bg_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Ops BG Abort"
      },
      {
       "expr": "sum by (service)( \nrate(aerospike_namespace_pi_query_ops_bg_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Ops BG Error"
      }
     ]
    },
    {
     "title": "SI Query - Long, Short, Aggr, UDF (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (service)( rate(aerospike_namespace_si_query_long_basic_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Long Basic Abort"
      },
      {
       "expr": "sum by (service)( \nrate(aerospike_namespace_si_query_long_basic_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Long Basic Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_si_query_short_basic_timeout{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Short Basic Timeout"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_si_query_short_basic_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Short Basic Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_si_query_aggr_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Aggr Error"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_si_query_aggr_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Aggr Abort"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_si_query_udf_bg_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - UDF BG Abort"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_si_query_udf_bg_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - UDF BG Error"
      },
      {
       "expr": "sum by (service) ( rate(aerospike_namespace_si_query_ops_bg_abort{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]) \n)",
       "legendFormat": "{{service}} - Ops BG Abort"
      },
      {
       "expr": "sum by (service) ( \nrate(aerospike_namespace_si_query_ops_bg_error{ cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}} - Ops BG Error"
      }
     ]
    },
    {
     "title": "Migrations Progress - RX, TX",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum by (service) (aerospike_namespace_migrate_rx_partitions_remaining{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}} - RX Partitions"
      },
      {
       "expr": "sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{cluster_name=~\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}} - TX Partitions"
      }
     ]
    },
    {
     "title": "HWM Breaches (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (service, ns) (\n    rate(aerospike_namespace_hwm_breached {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval] )\n)",
       "legendFormat": "{{service}} : {{ns}}"
      }
     ]
    },
    {
     "title": "Evictions (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": " sum by (service) (rate(aerospike_namespace_evicted_objects{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{service}} - Evicted Objects"
      }
     ]
    },
    {
     "title": "Latencies > $latency_time_bucket ms",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "(aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=\"+Inf\"})\n- ignoring (le)\n(aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=\"$latency_time_bucket\"})",
       "legendFormat": "{{service}} - {{ns}} - Write : {{le}}"
      }
     ]
    },
    {
     "title": "Reads Not Found - Batch, Clients (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum by (service) (rate( aerospike_namespace_batch_sub_read_not_found{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval] ))",
       "legendFormat": "{{service}} - Batch Sub"
      },
      {
       "expr": "sum by (service)(rate(aerospike_namespace_client_read_not_found{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{service}} - Client "
      }
     ]
    },
    {
     "title": "Partitions - Dead, Unavailable",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": " sum by (service) ((aerospike_namespace_unavailable_partitions{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}))",
       "legendFormat": "{{service}} - Unavailable"
      },
      {
       "expr": " sum by (service) ((aerospike_namespace_dead_partitions{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}))",
       "legendFormat": "{{service}} - Dead"
      }
     ]
    },
    {
     "title": "Duplicate Resolutions - Ask, Respond, No Read (rate)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum by (service) (rate(aerospike_namespace_dup_res_ask{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{service}} - Ask"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_dup_res_respond_read{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{service}} - Respond Read"
      },
      {
       "expr": "sum by (service) (rate(aerospike_namespace_dup_res_respond_no_read{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{service}} - Respond No Read"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources - Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Data Used (vs Size) (TopK) ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "topk($topk_limit, \n    (aerospike_namespace_device_used_bytes{cluster_name=\"$cluster\"}\n    /aerospike_namespace_device_total_bytes{cluster_name=\"$cluster\"}\n    )*100\n)",
       "legendFormat": "device - {{service}} - {{ns}}"
      },
      {
       "expr": "topk($topk_limit, \n    (aerospike_namespace_data_used_bytes{cluster_name=\"$cluster\" ,service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n    /aerospike_namespace_data_total_bytes{cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n    )*100\n)",
       "legendFormat": "{{service}} - {{ns}}"
      }
     ]
    },
    {
     "title": "% Data - Used, Available (TopK) ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "topk($topk_limit, 100 - aerospike_namespace_pmem_free_pct{cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "{{service}} -Used : {{ns}}"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_pmem_available_pct{cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "{{service}} - Available : {{ns}}"
      },
      {
       "expr": "topk($topk_limit, 100 - aerospike_namespace_device_free_pct{cluster_name=\"$cluster\"} )",
       "legendFormat": "{{service}} - Used : {{ns}}"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_device_available_pct{cluster_name=\"$cluster\"} )",
       "legendFormat": "{{service}} - Available : {{ns}}"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_data_used_pct{cluster_name=\"$cluster\"} )",
       "legendFormat": "{{service}} - Used : {{ns}}"
      },
      {
       "expr": "topk($topk_limit, aerospike_namespace_data_avail_pct{cluster_name=\"$cluster\"} )",
       "legendFormat": "{{service}} - Available : {{ns}}"
      }
     ]
    },
    {
     "title": "% Memory Used (vs Size) (TopK) (deprecated)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "topk($topk_limit, \n    (aerospike_namespace_memory_used_bytes{cluster_name=\"$cluster\" ,service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n    /aerospike_namespace_memory_size{cluster_name=\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n    )*100\n)",
       "legendFormat": "{{service}} - {{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources - OS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "% CPU - Process, Total, User, Kernel",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "topk($topk_limit,\nsum by (service) (aerospike_node_stats_process_cpu_pct{cluster_name=\"$cluster\",service=~\"$node|$^\"}) \n)",
       "legendFormat": "{{service}} - Process"
      },
      {
       "expr": "topk ($topk_limit,\nsum by (service) (aerospike_node_stats_system_total_cpu_pct{cluster_name=\"$cluster\",service=~\"$node|$^\"}) \n)",
       "legendFormat": "{{service}} - Total"
      },
      {
       "expr": "topk($topk_limit,\nsum by (service) ( aerospike_node_stats_system_user_cpu_pct{cluster_name=\"$cluster\",service=~\"$node|$^\"}) \n)",
       "legendFormat": "{{service}} - User"
      },
      {
       "expr": "topk($topk_limit,\nsum by (service) ( aerospike_node_stats_system_kernel_cpu_pct{cluster_name=\"$cluster\",service=~\"$node|$^\"}) )",
       "legendFormat": "{{service}} - Kernel"
      }
     ]
    },
    {
     "title": "% Heap - Allocated, Active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "topk($topk_limit, \nsum by (service) (\n  aerospike_node_stats_heap_allocated_kbytes{cluster_name=~\"$cluster\", service=~\"$node|$^\"})\n)",
       "legendFormat": "{{service}} - Allocated"
      },
      {
       "expr": "topk($topk_limit, \nsum by (service) (\n  aerospike_node_stats_heap_active_kbytes{cluster_name=~\"$cluster\", service=~\"$node|$^\"})\n)",
       "legendFormat": "{{service}} - Active"
      },
      {
       "expr": "topk($topk_limit, \nsum by (service) (\n  aerospike_node_stats_heap_mapped_kbytes{cluster_name=~\"$cluster\", service=~\"$node|$^\"})\n)",
       "legendFormat": "{{service}} - Mapped"
      }
     ]
    },
    {
     "title": "% Free System Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($topk_limit, \nsum by (service) (\n  aerospike_node_stats_system_free_mem_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\"})\n)",
       "legendFormat": "{{service}} - Free"
      }
     ]
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Defrag Q",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (\naerospike_namespace_storage_engine_file_defrag_q{ cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}  \nor \naerospike_namespace_storage_engine_device_defrag_q{ cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "{{service}} - q "
    }
   ]
  },
  {
   "title": "Defrag - Reads & Writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (\naerospike_namespace_storage_engine_file_defrag_reads{ cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}  \nor \naerospike_namespace_storage_engine_device_defrag_reads{cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "{{service}} - Defrag Reads "
    },
    {
     "expr": "sum by (service) (\naerospike_namespace_storage_engine_file_defrag_writes{ cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}  \nor \naerospike_namespace_storage_engine_device_defrag_writes{ cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "{{service}} - Defrag Writes"
    }
   ]
  },
  {
   "title": "Effective Replication Factor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aerospike_namespace_effective_replication_factor{ cluster_name=~\"$cluster|$^\",service=~\"$node|$^\",ns=~\"$namespace|$^\"}  ",
     "legendFormat": "{{service}} - {{ns}}"
    }
   ]
  },
  {
   "title": "Fabric Send & Receive Rates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_bulk_send_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Bulk Send"
    },
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_bulk_recv_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Bulk Receive"
    },
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_rw_send_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Rw Send"
    },
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_rw_recv_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Rw Receive"
    },
    {
     "expr": "sum by (service)(aerospike_node_stats_fabric_ctrl_send_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Ctrl Send"
    },
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_ctrl_recv_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Ctrl Receive"
    },
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_meta_send_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Meta Send"
    },
    {
     "expr": "sum by (service) (aerospike_node_stats_fabric_meta_recv_rate{cluster_name=\"$cluster\",service=~\"$node|$^\",ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}} - Meta Receive"
    },
    {
     "expr": "aerospike_node_stats_fabric_bulk_send_rate ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}