{
 "title": "Secondary Index Summary",
 "description": "Secondary Index Summary dashboard provides information about overview of secondary index usage at namespace level.",
 "tags": [
  "usecase",
  "monitoring",
  "sindex"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_sindex_entries{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},ns)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sindex Count (total)",
   "type": "stat",
   "description": "Secondary index count",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (sindex) (aerospike_sindex_entries{job=\"$job_name\", cluster_name=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used (total) (bytes)",
   "type": "stat",
   "description": "Total bytes in-use on the mount(s) for the secondary indexes used by this namespace on this node.",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used (bytes)",
   "type": "bargauge",
   "description": "Displays minimum, average and maximum of  memory used by sindex across all namespaces",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (aerospike_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg (aerospike_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max (aerospike_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Garbage Collected (total)  (rate)",
   "type": "stat",
   "description": "Number of secondary index entries cleaned by sindex GC.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(aerospike_namespace_sindex_gc_cleaned{job=\"$job_name\", cluster_name=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Long Queries (max) (rate / one hour)",
   "type": "stat",
   "description": "Number of basic queries  that have been completed/aborted/errors after exceeding a predefined timeout duration within a namespace in sindex queries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Completed "
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Short Queries (max) (rate / one hour)",
   "type": "stat",
   "description": "Number of basic queries completed/timedout/errors in sindex queries within a namespace within a predefined short duration",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "UDF Queries (max) (rate / one hour)",
   "type": "stat",
   "description": "Number of udf background secondary index queries that were completed/sborted/errors",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Query Aggregations (max) (rate / one hour)",
   "type": "stat",
   "description": "Number of secondary index query aggregations completed/aborted/errors",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Ops Background Queries (max) (rate / one hour)",
   "type": "stat",
   "description": "Number of ops background secondary index queries completed/aborted/errors",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "max (rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\"}[1h]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Namespace - $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Sindex Count",
     "type": "stat",
     "description": "Memory, pmem and device type secondary index count",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (group by (sindex)(aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", storage_engine=\"pmem\"}))",
       "legendFormat": "pmem"
      },
      {
       "expr": "count (group by (sindex)(aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", storage_engine=\"device\"}))",
       "legendFormat": "device"
      },
      {
       "expr": "count (group by (sindex)(aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", storage_engine=\"memory\"}))",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "Memory Used (bytes)",
     "type": "stat",
     "description": "Total bytes in-use on the mount(s) for the secondary indexes used by this namespace on this node.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "% Memory Used ",
     "type": "stat",
     "description": "Applies only to Enterprise Edition configured with sindex-type pmem or flash, %memory used",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (aerospike_namespace_sindex_mounts_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Budget (bytes)",
     "type": "stat",
     "description": "Maximum mount budget allocated ",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_sindex_type_mounts_budget{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})",
       "legendFormat": " "
      },
      {
       "expr": "sum (aerospike_namespace_sindex_type_mounts_size_limit{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Garbage Collected (rate)",
     "type": "stat",
     "description": "Number of secondary index entries cleaned by sindex GC.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (ns) (rate(aerospike_namespace_sindex_gc_cleaned{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
       "legendFormat": "{{ns}}"
      }
     ]
    },
    {
     "title": "Memory Used (bytes)",
     "type": "timeseries",
     "description": "Total bytes in-use on the mount(s) for the secondary indexes used by this namespace on this node.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Budget (bytes)",
     "type": "timeseries",
     "description": "Maximum mount budget allocated ",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_sindex_type_mounts_budget{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})",
       "legendFormat": " {{service}}-{{sindex}}"
      },
      {
       "expr": "(aerospike_namespace_sindex_type_mounts_size_limit{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}-{{sindex}}"
      }
     ]
    },
    {
     "title": "Entries",
     "type": "timeseries",
     "description": "Number of secondary index entries for this secondary index. This is the number of records that have been indexed by this secondary index.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_sindex_entries{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}-{{sindex}}"
      }
     ]
    },
    {
     "title": "Entries Per Record",
     "type": "timeseries",
     "description": "Number of entries per secondary index per record",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_sindex_entries_per_rec{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}-{{sindex}}"
      }
     ]
    },
    {
     "title": "Entries Per Bin",
     "type": "timeseries",
     "description": "Number of entries per secondary index per bin value",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_sindex_entries_per_bval{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}-{{sindex}}"
      }
     ]
    },
    {
     "title": "Garbage Collected (rate)",
     "type": "timeseries",
     "description": "Number of secondary index entries cleaned by sindex GC.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_sindex_gc_cleaned{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Long Queries (rate)",
     "type": "timeseries",
     "description": "Number of basic queries  that have been completed/aborted/errors after exceeding a predefined timeout duration within a namespace in sindex queries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Completed "
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Aborted"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Errors"
      }
     ]
    },
    {
     "title": "Short Queries (rate)",
     "type": "timeseries",
     "description": "Number of basic queries completed/timedout/errors in sindex queries within a namespace within a predefined short duration",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Completed"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Timeout"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Errors"
      }
     ]
    },
    {
     "title": "Ops Background Queries (rate)",
     "type": "timeseries",
     "description": "Number of ops background secondary index queries completed/aborted/errors",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Completed"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Aborted"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Errors"
      }
     ]
    },
    {
     "title": "UDF Queries (rate)",
     "type": "timeseries",
     "description": "Number of udf background secondary index queries that were completed/sborted/errors",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Completed"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Aborted"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Errors"
      }
     ]
    },
    {
     "title": "Query Aggregations (rate)",
     "type": "timeseries",
     "description": "Number of secondary index query aggregations completed/aborted/errors",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Completed"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Aborted"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}-Errors"
      }
     ]
    }
   ]
  }
 ]
}