{
 "title": "Aerospike Backup Service",
 "description": "This dashboard helps to visualise the aerospike backup service statistics.",
 "tags": [
  "aerospike",
  "monitoring",
  "Backup"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_backup_service_backup_events_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aerospike_backup_service_backup_events_total{job=~\"$job_name\"},instance)"
    }
   },
   { "name": "type", "label": "Type", "query": "full,incremental" },
   {
    "name": "copy_of_type",
    "label": "Type",
    "query": {
     "query": "label_values(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\"},type)"
    }
   },
   {
    "name": "routine",
    "label": "Routine",
    "query": {
     "query": "label_values(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\"},routine)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services (count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (aerospike_backup_service_restore_in_progress{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Success (sum)",
   "type": "stat",
   "description": "Total backup success count, \nTotal incremental backup success count.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\", outcome=\"success\", routine=~\"$routine\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Failures (sum)",
   "type": "stat",
   "description": "Total backup failures, \nTotal  incremental  backup failures.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=\"failure\", routine=~\"$routine\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cancel (sum)",
   "type": "stat",
   "description": "Total backup retries, \nTotal incremental backup retries.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=~\"cancel.*\", routine=~\"$routine\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Skip (sum)",
   "type": "stat",
   "description": "Total backup skip, \nTotal  incremental  backup skip.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=\"skip\", routine=~\"$routine\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Retry (sum)",
   "type": "stat",
   "description": "Total backup retries, \nTotal incremental backup retries.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=~\"retry\", routine=~\"$routine\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Full - Backup duration (percentiles)",
   "type": "stat",
   "description": "Full and incremental backup duration buckets.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.5, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)full\", })))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg (histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)full\", })))",
     "legendFormat": "p95"
    },
    {
     "expr": "avg (histogram_quantile(0.99, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)full\", })))",
     "legendFormat": "p99"
    },
    {
     "expr": "avg (histogram_quantile(0.999, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)full\", })))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "Incremental - Backup duration (percentiles)",
   "type": "stat",
   "description": "Full and incremental backup duration buckets.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.5, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
     "legendFormat": "p50"
    },
    {
     "expr": "avg (histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
     "legendFormat": "p95"
    },
    {
     "expr": "avg (histogram_quantile(0.99, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
     "legendFormat": "p99"
    },
    {
     "expr": "avg (histogram_quantile(0.999, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
     "legendFormat": "p999"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Last Successful",
     "type": "stat",
     "description": "Total backup success count, \nTotal incremental backup success count.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type) (aerospike_backup_service_last_successful_backup_timestamp{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\", routine=~\"$routine\"})*1000",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Success (sum)",
     "type": "stat",
     "description": "Total backup success count, \nTotal incremental backup success count.",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=\"success\",routine=~\"$routine\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Cancel (sum)",
     "type": "stat",
     "description": "Total backup retries, \nTotal incremental backup retries.",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=\"cancel.*\",routine=~\"$routine\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Retry (sum)",
     "type": "stat",
     "description": "Total backup retries, \nTotal incremental backup retries.",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type)(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=~\"retry\", routine=~\"$routine\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Failures (sum)",
     "type": "stat",
     "description": "Total backup failures, \nTotal  incremental  backup failures.",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type)(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=~\"failure\", routine=~\"$routine\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Skip (sum)",
     "type": "stat",
     "description": "Total backup skip, \nTotal  incremental  backup skip.",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (type) (aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", type=~\"$type\",outcome=~\"skip\", routine=~\"$routine\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Full - Backup duration (percentiles)",
     "type": "stat",
     "description": "Full and incremental backup duration buckets.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (histogram_quantile(0.5, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", })))",
       "legendFormat": "p50"
      },
      {
       "expr": "avg (histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", })))",
       "legendFormat": "p95"
      },
      {
       "expr": "avg (histogram_quantile(0.99, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", })))",
       "legendFormat": "p99"
      },
      {
       "expr": "avg (histogram_quantile(0.999, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", })))",
       "legendFormat": "p999"
      }
     ]
    },
    {
     "title": "Incremental - Backup duration (percentiles)",
     "type": "stat",
     "description": "Full and incremental backup duration buckets.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (histogram_quantile(0.5, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
       "legendFormat": "p50"
      },
      {
       "expr": "avg (histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
       "legendFormat": "p95"
      },
      {
       "expr": "avg (histogram_quantile(0.99, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
       "legendFormat": "p99"
      },
      {
       "expr": "avg (histogram_quantile(0.999, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", })))",
       "legendFormat": "p999"
      }
     ]
    },
    {
     "title": "%  Backup Progress",
     "type": "timeseries",
     "description": "Progress of full and incremental backup processes in percentage",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_backup_service_backup_progress_pct{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\",type=~\"(?i)$type\"}",
       "legendFormat": " {{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Backup duration - incremental (rate) (ms)",
     "type": "timeseries",
     "description": "Incremental backup duration in milliseconds",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(rate(aerospike_backup_service_backup_duration_seconds_sum{job=~\"$job_name\", instance=~\"$instance\",routine=~\"$routine\", type=~\"incremental\"}[$__rate_interval]))",
       "legendFormat": "{{routine}}"
      }
     ]
    },
    {
     "title": "Backup duration - full (rate) (ms)",
     "type": "timeseries",
     "description": " Full backup duration in milliseconds",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(rate(aerospike_backup_service_backup_duration_seconds_sum{job=~\"$job_name\", instance=~\"$instance\",routine=~\"$routine\", type=~\"(?i)full\"}[$__rate_interval]))",
       "legendFormat": "{{routine}}"
      }
     ]
    },
    {
     "title": "Success - incremental (rate)",
     "type": "timeseries",
     "description": "Total incremental backup success.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\",outcome=\"success\", type=~\"incremental\"}[$__rate_interval])",
       "legendFormat": " {{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Success - full (rate)",
     "type": "timeseries",
     "description": "Total full backup success.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\",outcome=\"success\", type=~\"(?i)full\"}[$__rate_interval])",
       "legendFormat": "{{routine}}"
      }
     ]
    },
    {
     "title": "Failure - incremental (rate)",
     "type": "timeseries",
     "description": "Total incremental backup failures.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", outcome=\"failure\", routine=~\"$routine\", type=~\"incremental\"}[$__rate_interval])",
       "legendFormat": " {{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Failure - full (rate)",
     "type": "timeseries",
     "description": "Total full backup failures.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", outcome=\"failure\", routine=~\"$routine\", type=~\"(?i)full\"}[$__rate_interval])",
       "legendFormat": " {{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Retry - incremental (rate)",
     "type": "timeseries",
     "description": "Total incremental backup retries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\",routine=~\"$routine\",  outcome=~\"retry\",  type=~\"(?i)incremental\"}[$__rate_interval])",
       "legendFormat": "{{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Retry - full (rate)",
     "type": "timeseries",
     "description": "Total full backup retries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\",routine=~\"$routine\",  outcome=~\"retry\",  type=~\"(?i)full\"}[$__rate_interval])",
       "legendFormat": "{{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Skip - incremental (rate)",
     "type": "timeseries",
     "description": "Total incremental backup skipped.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", outcome=\"skip\", routine=~\"$routine\", type=~\"(?i)incremental\"}[$__rate_interval])",
       "legendFormat": "{{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Skip - full (rate)",
     "type": "timeseries",
     "description": "Total full backup skipped.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_backup_events_total{job=~\"$job_name\", instance=~\"$instance\", outcome=\"skip\", routine=~\"$routine\", type=~\"(?i)full\"}[$__rate_interval])",
       "legendFormat": "{{type}} : {{routine}}"
      }
     ]
    },
    {
     "title": "Restore in Progress (rate)",
     "type": "timeseries",
     "description": "Number of restore processes are running",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_backup_service_restore_in_progress{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Full - Backup duration by Routine (percentiles)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routine",
     "type": "stat",
     "description": "Full and incremental backup duration buckets.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 175 },
     "repeat": "routine",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", }))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", }))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", }))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)full\", }))",
       "legendFormat": "p999"
      }
     ]
    }
   ]
  },
  {
   "title": "Incremental - Backup duration by Routine (percentiles)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$routine",
     "type": "stat",
     "description": "Full and incremental backup duration buckets.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 632 },
     "repeat": "routine",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", }>0))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", }>0))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", }))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, (aerospike_backup_service_backup_duration_seconds_bucket{job=~\"$job_name\", instance=~\"$instance\", routine=~\"$routine\", type=~\"(?i)incremental\", }))",
       "legendFormat": "p999"
      }
     ]
    }
   ]
  }
 ]
}