{
 "title": "Multi Cluster View",
 "description": "Multi Cluster view dashboard helps visualise multiple clusters across regions and data centers with focus on health as well as alerts and errors associated with them",
 "tags": [
  "usecase",
  "cluster",
  "monitoring",
  "topology"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster\" },service)"
    }
   },
   {
    "name": "severity",
    "label": "Alert Severity",
    "query": {
     "query": "label_values(ALERTS{job=\"$job_name\", },severity)"
    }
   },
   {
    "name": "mermaid_text",
    "label": "Topology definitions",
    "query": {
     "query": "query_result( ( label_join(label_join (label_join  (label_join( label_join(label_replace( label_replace( ((count_values by (cluster_name, dc, ns) ( \"xdr_bytes\", sum by (cluster_name, dc, ns) (aerospike_xdr_bytes_shipped{} and aerospike_xdr_dc_namespace_enabled{}==1)  ) + on (cluster_name,  dc, ns ) group_left(xdr_lag) count_values by (cluster_name, dc, ns) ( \"xdr_lag\", max by (cluster_name, dc, ns) (aerospike_xdr_lag{} and aerospike_xdr_dc_namespace_enabled{}==1 )  ) + on (cluster_name, ns ) group_left(ns_objects) count_values by (cluster_name, ns) ( \"ns_objects\", sum by (cluster_name, ns) (aerospike_namespace_objects{})) )), \"dc\", \",$1[$1];\", \"dc\", \"(.*)\"), \"cluster_name\", \"$1[$1]\", \"cluster_name\", \"(.*)\")\t\t, \"L1\", \",\", \"cluster_name\"),\"L1\",\"==Namespace: \", \"L1\", \"ns\" ),\"L1\",\"<br>Bytes: \", \"L1\", \"xdr_bytes\" )   ,\"L1\",\"<br>Max. Lag: \", \"L1\", \"xdr_lag\" )  ,\"L1\", \"==>\", \"L1\", \"dc\" ) or on() label_join(label_replace(  (count_values by (cluster_name, ns) ( \"ns_objects\", sum by (cluster_name, ns) (aerospike_namespace_objects{})) ) , \"cluster_name\", \"$1[($1)];\", \"cluster_name\", \"(.*)\") , \"L1\", \",\", \"cluster_name\") or on() label_replace( count_values(\"xdr_data_absent\", (absent(aerospike_xdr_dc_namespace_enabled{}))),\"L1\",\"no-data[no data]\", \"no_data\", \"(.*)\" ) ))"
    }
   },
   {
    "name": "servers_mermaid_text",
    "label": "Topology definitions",
    "query": {
     "query": "query_result( (  label_join(label_replace(  (count_values by (cluster_name, ns) ( \"ns_objects\", sum by (cluster_name, ns) (aerospike_namespace_objects{})) ) , \"cluster_name\", \"$1[($1)];\", \"cluster_name\", \"(.*)\") , \"L1\", \",\", \"cluster_name\") or label_replace( count_values(\"no_ns_objects\", (absent(aerospike_namespace_objects{}))),\"L1\",\"no-data[no data]\", \"no_data\", \"(.*)\" )))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Geo Locations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "geomap",
   "description": "To enable geomap, set cluster_name, longitude and latitude labels on your exporter.\nNOTE: This panel requires Polystat plugin",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (latitude, longitude, cluster_name) (ALERTS{cluster_name!=\"\", job=\"aerospike\", severity=~\"critical|warn\"}) * -1\nor\ncount by (latitude, longitude, cluster_name) (aerospike_node_up)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Replication topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "jdbranham-diagram-panel",
     "description": "Displays topology of the connected aerospike servers across data centers, this diagram panel is dependent on cluster-name and the xdr names configured in the aerospike configuration files. This panel requires the diagram-panel plugin.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": {
      "content": "graph LR\n%% START Comment\n%% Below line starts with a comma because other IP are coming with a comma becuase of Grafana advanced formatting \"raw\" appending a multi-list variable\n%% END Comment\n,${mermaid_text:raw};\n,${servers_mermaid_text:raw};"
     },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Cluster Details - $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "cluster" },
  {
   "title": "Cluster Size (Unique values)",
   "type": "stat",
   "description": "Displays the number of aerospike nodes configured within a cluster, in case if there is a condition like split-brain or different cluster-sizes reported, this panel displays different values indicating issues",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values (\"size\", (aerospike_node_stats_cluster_size{cluster_name=\"$cluster\"}) )",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "piechart",
   "description": "Alert count",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity) (ALERTS{job=\"$job_name\",cluster_name=~\"$cluster\", severity=~\"$severity\"}) or vector(0)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "$cluster - Nodes",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "count by (service,cluster_name) (ALERTS{cluster_name=\"$cluster\", service!=\"\", severity=~\"critical|warn\"}) * -1\nor\ncount by (service,cluster_name) (aerospike_node_up{ cluster_name=\"$cluster\"})",
     "legendFormat": "{{service}}:{{cluster_name}}"
    }
   ]
  },
  {
   "title": "$cluster - Namespaces",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count by (ns) (ALERTS{cluster_name=\"$cluster\", ns=~\"..*\", severity=~\"critical|warn\"}) * -1 \n* on (ns) group_left\nsum by (ns) (aerospike_namespace_objects{cluster_name=\"$cluster\"} ))\nor\nsum by (ns) (aerospike_namespace_objects{cluster_name=\"$cluster\"} ) \n",
     "legendFormat": "{{ns}}"
    }
   ]
  },
  {
   "title": "XDR Lag (max)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " max(aerospike_xdr_lag{cluster_name=~\"$cluster\"}) ",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Latencies (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", le=\"+Inf\"})\n- \nsum (aerospike_latencies_write_ms_bucket{cluster_name=~\"$cluster\", le=\"4\"}) ",
     "legendFormat": "Write > 4ms"
    },
    {
     "expr": "sum (aerospike_latencies_read_ms_bucket{cluster_name=~\"$cluster\", le=\"+Inf\",}) \n- \nsum (aerospike_latencies_read_ms_bucket{cluster_name=~\"$cluster\", le=\"4\",}) ",
     "legendFormat": "Read > 4ms"
    }
   ]
  }
 ]
}