{
 "title": "Secondary Index View",
 "description": "Secondary Index dashboard provides secondary index as well as helping in tracking and setting specific sindex quotas.",
 "tags": [ "sindex" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\" },ns)"
    }
   },
   {
    "name": "sindex",
    "label": "Secondary Index",
    "query": {
     "query": "label_values(aerospike_sindex_entries{job=\"$job_name\", cluster_name=~\"$cluster|$^\", ns=~\"$namespace|$^\" },sindex)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Secondary Index Name",
   "type": "text",
   "description": "Secondary Index Name",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1 style=\"color:#299c46;\">$sindex</h1></center>"
   }
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "description": "Amount of memory, in bytes, consumed by the secondary index.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_sindex_memory_used{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"})\nor \navg(aerospike_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"})",
     "legendFormat": "memory_used"
    }
   ]
  },
  {
   "title": "Entries/Bins",
   "type": "stat",
   "description": "Ratio of secondary index entries to unique bin values. This uses the aerospike_sindex_entries_per_bval metric.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sindex_entries_per_bval{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"})",
     "legendFormat": "Entries/Bins"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "timeseries",
   "description": "Number of records that have been garbage collected out of the secondary index memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(aerospike_sindex_stat_gc_recs{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"}[5m]))",
     "legendFormat": "Record count"
    }
   ]
  },
  {
   "title": "Load percentage",
   "type": "gauge",
   "description": "Progress in percentage of the creation of secondary index",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_sindex_load_pct{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"})",
     "legendFormat": "load_pct"
    }
   ]
  },
  {
   "title": "Max Load Time",
   "type": "stat",
   "description": "Maximum time it took for the secondary index to be fully created",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_sindex_load_time{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"})",
     "legendFormat": "loadtime"
    }
   ]
  },
  {
   "title": "Entries",
   "type": "stat",
   "description": "Number of secondary index entries for this secondary index. This is the number of records that have been indexed by this secondary index.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sindex_entries{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"}) / max(aerospike_namespace_effective_replication_factor{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Entries"
    }
   ]
  },
  {
   "title": "Entries/Records",
   "type": "stat",
   "description": "Ratio of secondary index entries to unique records. This is always 1 unless the sindex is on a list or map. This uses the aerospike_sindex_entries_per_rec metric.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sindex_entries_per_rec{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\", sindex=~\"$sindex\"})",
     "legendFormat": "Entries/Record"
    }
   ]
  }
 ]
}