{
 "title": "Unique Data Usage",
 "description": "Unique Data dashboard, display the master objects and bytes consumed at both cluster level and each namespace in the cluster",
 "tags": [
  "usecase",
  "license"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Clusters - Summary ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Cluster - Master Objects (total)",
   "type": "stat",
   "description": "Display Unique Data Utilization across all cluster and namespaces connected to this prometheus instance",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$Q_MEMORY_OBJECTS * $QR_RULE_CAN_SHOW",
     "type": "math"
    }
   ]
  },
  {
   "title": "All Clusters - Unique Data Bytes (total)",
   "type": "stat",
   "description": "Display Unique Data Utilization across all  cluster and namespaces connected to this prometheus instance",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($6_Q_USAGE_BYTE + $7_Q_USAGE_BYTE) * $QR_RULE_CAN_SHOW",
     "type": "math"
    }
   ]
  },
  {
   "title": "Clusters wise - Historical - Usage Bytes",
   "type": "timeseries",
   "description": "Display Unique Data Utilization across all  cluster and namespaces connected to this prometheus instance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "($6_Q_USAGE_BYTE ) * $QR_RULE_CAN_SHOW",
     "type": "math"
    },
    {
     "expression": "($7_Q_USAGE_BYTE ) * $QR_RULE_CAN_SHOW",
     "type": "math"
    }
   ]
  },
  {
   "title": "Cluster - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster - All Master Objects",
     "type": "stat",
     "description": "Display Unique Data Utilization across all  namespaces",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$Q_MEMORY_OBJECTS ", "type": "math" }
     ]
    },
    {
     "title": "Cluster - Unique Data Bytes ",
     "type": "stat",
     "description": "Display Unique Data Utilization across all  namespaces",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($6_Q_USAGE_BYTE + $7_Q_USAGE_BYTE) * $QR_RULE_CAN_SHOW",
       "type": "math"
      }
     ]
    }
   ]
  },
  {
   "title": "Historical - Usage Bytes - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Historical - Usage Bytes",
     "type": "timeseries",
     "description": "Display Unique Data Utilization across all  namespaces",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expression": "($6_Q_USAGE_BYTE + $7_Q_USAGE_BYTE ) * $QR_RULE_CAN_SHOW",
       "type": "math"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespace - $namespace",
     "type": "stat",
     "description": "Display Unique Data Utilization by namespaces in bytes",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
     "repeat": "namespace",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum (aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}) by (ns) )  ",
       "legendFormat": "master objects - "
      },
      {
       "expression": "$Q_MEMORY_USAGE * $QR_RULE_CAN_SHOW",
       "type": "math"
      },
      {
       "expression": "$Q_DISK_USAGE * $QR_RULE_CAN_SHOW",
       "type": "math"
      },
      {
       "expression": "$Q_PMEM_DISK_USAGE * $QR_RULE_CAN_SHOW",
       "type": "math"
      },
      {
       "expr": "(sum((sum((sum ( (((aerospike_namespace_data_used_bytes {job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"} ) /\naerospike_namespace_data_compression_ratio {job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}\n) \n/aerospike_namespace_effective_replication_factor {job=\"$job_name\", cluster_name=~\"$cluster\", ns=~\"$namespace|$^\"}\n) \n) by (service, ns))  ) by (ns))) \n\n) # end paranthesis for whole sum",
       "legendFormat": "Unique Bytes -"
      }
     ]
    }
   ]
  }
 ]
}