{
 "title": "Users View",
 "description": "User View dashboard helps visualise user centric metrics like connections,read query ,write query etc.",
 "tags": [ "users" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(aerospike_users_conns_in_use{job=\"$job_name\"},user)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_conns_in_use{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Read Single Record TPS",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_read_single_record_tps{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Write Single Record TPS",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_write_single_record_tps{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Read Scan RPS",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_read_scan_query_rps{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Write Scan RPS",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_write_scan_query_rps{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Limitless Read Scan/Query",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_limitless_read_scan_query{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Limitless Write Scan/Query",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_limitless_write_scan_query{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Read Quota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_read_quota{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Write Quota",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_users_write_quota{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", user=~\"$user\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}