{
 "title": "XDR View (Aerospike 5.0+ only)",
 "description": "XDR Dashboard displays key metrics like lag, bytes-shipped related to the data backup and transfer status between each data-center and namespaces configuted",
 "tags": [
  "xdr",
  "monitoring",
  "backup"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "dc",
    "label": "DC",
    "query": {
     "query": "label_values(aerospike_xdr_lap_us{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },dc)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XDR Statistics Summary",
   "type": "stat",
   "description": "Total Throughput (sum across all namespaces and all DCs)\n\nAverage XDR Lag\n\nAverage Ship Latency\n\nAverage Lap us (Time taken to process records across partitions in one lap)\n\nTotal recoveries pending\n\nTotal In Progress\n\nTotal In Queue",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_xdr_throughput{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total Throughput"
    },
    {
     "expr": "avg(aerospike_xdr_lag{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Avg Lag"
    },
    {
     "expr": "avg(aerospike_xdr_latency_ms{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Avg Ship Latency"
    },
    {
     "expr": "avg(aerospike_xdr_lap_us{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Avg Lap us"
    },
    {
     "expr": "sum(aerospike_xdr_recoveries_pending{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total Recoveries Pending"
    },
    {
     "expr": "sum(aerospike_xdr_in_progress{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total In Progress"
    },
    {
     "expr": "sum(aerospike_xdr_in_queue{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"})",
     "legendFormat": "Total In Queue"
    },
    {
     "expr": "sum(rate(aerospike_xdr_bytes_shipped{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m]))",
     "legendFormat": "Total bytes shipped"
    }
   ]
  },
  {
   "title": "DC Nodes",
   "type": "stat",
   "description": "Number of nodes in the destination DC as seen by XDR (Average)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aerospike_xdr_nodes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", dc=~\"$dc\"}) by (dc)",
     "legendFormat": "{{dc}}"
    }
   ]
  },
  {
   "title": "Host TCP Connections (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (aerospike_sysinfo_netstat_tcp_activeopens{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "sum (aerospike_sysinfo_netstat_tcp_currestab{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "Established"
    }
   ]
  },
  {
   "title": "Host Network Traffic - retransmit (packets) (total) (rate)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(aerospike_sysinfo_netstat_tcp_retranssegs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval] ))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Network Traffic (bytes) (total) (rate)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(aerospike_sysinfo_network_receive_bytes_total{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", }[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (irate(aerospike_sysinfo_network_transfer_bytes_total{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", }[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Detailed Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "XDR throughput",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_throughput{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Throughput {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Success",
     "type": "timeseries",
     "description": "Number of records successfully shipped",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[1m])",
       "legendFormat": "Success {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Abandoned (rate)",
     "type": "timeseries",
     "description": "Number of ships abandoned",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_abandoned{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Abandoned {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Not Found (rate)",
     "type": "timeseries",
     "description": "Number of XDR local read not found",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Not found {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Filtered Out (rate)",
     "type": "timeseries",
     "description": "How many records are skipped after XDR reading the record locally but before putting them on wire",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Filtered out {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Retry Connection Reset (rate)",
     "type": "timeseries",
     "description": "Number of retries due to connection reset",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_retry_conn_reset{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Retry Conn Reset {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Retry Destination (rate)",
     "type": "timeseries",
     "description": "Number of retries due to temporary error from destination",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_retry_dest{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Retry Destination {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Hot Keys (rate)",
     "type": "timeseries",
     "description": "Number of times a record write is skipped from processing because that record is already pending processing",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_hot_keys{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Hot keys {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "In Progress",
     "type": "timeseries",
     "description": "Number of XDR processing record in progress",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_in_progress{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "In Progress {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "In Queue",
     "type": "timeseries",
     "description": "Number of records waiting to be processed in in-memory transaction queue",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_in_queue{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "In queue {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Lag",
     "type": "timeseries",
     "description": "It signifies how much behind the destination is compared to the source. In other words, so much time worth of data is yet to be shipped from source to destination",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_lag{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Lag {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Lap μs",
     "type": "timeseries",
     "description": "Time taken to process records across partitions in one lap. A higher number indicates slowness of source in processing the records.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_lap_us{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Lap μs {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Recoveries (rate)",
     "type": "timeseries",
     "description": "Number of partitions that are recovered by reducing the primary index of that partition",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_recoveries{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": "Recoveries {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Recoveries Pending",
     "type": "timeseries",
     "description": "Number of recoveries that are currently pending",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_recoveries_pending{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Recoveries pending {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Latency ms",
     "type": "timeseries",
     "description": "Average network latency for the successfully shipped records",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_latency_ms{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Latency ms {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Avg Compression Ratio",
     "type": "timeseries",
     "description": "Average XDR compression ratio",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_compression_ratio{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Avg compression ratio {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Uncompressed Pct",
     "type": "timeseries",
     "description": "How much % of records are not compressed because they are below the compression threshold",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_xdr_uncompressed_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}",
       "legendFormat": "Uncompressed pct {{service}} {{dc}}"
      }
     ]
    },
    {
     "title": "Bytes Shipped (rate)",
     "type": "timeseries",
     "description": "Number of bytes shipped for a namespace to a DC by XDR.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_bytes_shipped{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", dc=~\"$dc|$^\"}[$__rate_interval])",
       "legendFormat": " {{service}} {{dc}} "
      }
     ]
    }
   ]
  },
  { "title": "Resources - Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Host TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": " (aerospike_sysinfo_netstat_tcp_activeopens{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "{{service}}: Open"
    },
    {
     "expr": " (aerospike_sysinfo_netstat_tcp_currestab{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"})",
     "legendFormat": "{{service}}: Established"
    }
   ]
  },
  {
   "title": "Host Network Traffic - retransmit (packets)  (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " (irate(aerospike_sysinfo_netstat_tcp_retranssegs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval] ))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Network Traffic - Received (bytes) (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (service) (irate(aerospike_sysinfo_network_receive_bytes_total{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", }[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Host Network Traffic - Transmitted (bytes) (rate)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (service) (irate(aerospike_sysinfo_network_transfer_bytes_total{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", }[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}