{
 "title": "Aerospike Kubernetes Operator View",
 "description": "This dashboard visualizes the controller-runtime and workqueue metrics. It provides insights into the performance, behavior, and reconciliation efficiency of the Aerospike Operator.",
 "tags": [
  "AKO",
  "kubernetes",
  "monitoring",
  "operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(controller_runtime_active_workers,job)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{job=~\"$job_name\"},controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;background-color:rgb(4, 123, 196);font-size:25px\"><b>System</b></p>\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;background-color:rgb(4, 123, 196);font-size:25px\"><b>REST Clients</b></p>\n\n"
   }
  },
  {
   "title": "Operator Uptime",
   "type": "stat",
   "description": "This panel shows the uptime of the operator.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds {job=~\"$job_name\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success (rate) (total)",
   "type": "stat",
   "description": "Total number of successful REST client requests.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=~\"$job_name\", code=~\"2..\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Failures (rate) (total)",
   "type": "stat",
   "description": "Total number of failure REST client requests.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum  by (code) (rate(rest_client_requests_total{job=~\"$job_name\", code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 7 },
   "options": {
    "content": "<p style=\"text-align:center;background-color:rgb(4, 123, 196);font-size:25px\"><b>Webhook Requests </b></p>\n\n"
   }
  },
  {
   "title": "Leader Status ",
   "type": "stat",
   "description": "Shows the current leader\nwhich handles the requests.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "leader_election_master_status{job=~\"$job_name\"} >0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success (rate) (total)",
   "type": "stat",
   "description": "Total number of Successful webhook\nrequests.",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (code) (rate(controller_runtime_webhook_requests_total{job=\"$job_name\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Failures (rate) (total)",
   "type": "stat",
   "description": "Total number of failure webhook\nrequests.",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sum by (code) (rate(controller_runtime_webhook_requests_total{job=\"$job_name\", code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "In Flight (total)",
   "type": "stat",
   "description": "Current number\nof admission\nrequests being\nserved.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "targets": [
    {
     "expr": "sum(controller_runtime_webhook_requests_in_flight {job=~\"$job_name\", webhook=~\".*\"}) ",
     "legendFormat": "  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<p style=\"text-align:center;background-color:rgb(4, 123, 196);font-size:25px\"><b>Controller (total)</b></p>\n\n"
   }
  },
  {
   "title": "Workqueue Depth",
   "type": "stat",
   "description": "Displays the total workqueue depth (pending items) of each controller.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{job=\"$job_name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Longest Running Time",
   "type": "stat",
   "description": "Total duration (in seconds) of the longest-running workqueue processor for each controller.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_longest_running_processor_seconds{job=~\"$job_name\",})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "stat",
   "description": "Shows how many workers are currently processing tasks for each controller. ",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (controller)(controller_runtime_active_workers{job=\"$job_name\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Errors (rate)",
   "type": "stat",
   "description": "Total number of reconciliation errors per\ncontroller.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (controller)(rate(controller_runtime_reconcile_errors_total{job=\"$job_name\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": " $controller Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "controller",
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "description": "Current depth of workqueue workers per controller.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "workqueue_depth{job=~\"$job_name\", name=~\"$controller\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Longest Runnig Processor Seconds",
     "type": "timeseries",
     "description": "Duration (in seconds) of the longest-running workqueue processor. Helps identify processing delays.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "workqueue_longest_running_processor_seconds{job=~\"$job_name\", name=~\"$controller\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Retries (rate)",
     "type": "timeseries",
     "description": "Total number of retries handled by workqueue.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(workqueue_retries_total{job=~\"$job_name\", name=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Unfinished Work Seconds",
     "type": "timeseries",
     "description": "How many seconds of work has been done that is in progress and hasn’t been observed by work_duration.Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "workqueue_unfinished_work_seconds{job=~\"$job_name\", name=~\"$controller\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Adds (rate)",
     "type": "timeseries",
     "description": "Total number of adds handled by workqueue.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(workqueue_adds_total{job=~\"$job_name\", name=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Workqueue Queue Duration",
     "type": "heatmap",
     "description": "How long in seconds an item stays in workqueue before being requested",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by (le)(workqueue_queue_duration_seconds_bucket{job=~\"$job_name\", name=~\"$controller\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Workqueue Work Duration",
     "type": "heatmap",
     "description": "How long in seconds processing an item from workqueue takes.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by (le)(workqueue_work_duration_seconds_bucket{job=~\"$job_name\", name=~\".*$controller\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Webhook Latency Duration",
     "type": "heatmap",
     "description": "Latency of processing admission requests.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (le) (controller_runtime_webhook_latency_seconds_bucket{job=\"$job_name\", webhook=~\".*$controller\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Reconcile Duration",
     "type": "heatmap",
     "description": "Time per reconciliation per controller before being requested from the workqueue.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by (le)(controller_runtime_reconcile_time_seconds_bucket{job=~\"$job_name\", controller=~\"$controller\"})",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Active Workers",
     "type": "timeseries",
     "description": "Number of currently used workers per controller.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "controller_runtime_active_workers{job=\"$job_name\", controller=~\"$controller\"}",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Reconcile (rate)",
     "type": "timeseries",
     "description": "Total number of reconciliations per controller.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_total{job=\"$job_name\", controller=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Reconcile & Terminal Errors (rate)",
     "type": "timeseries",
     "description": "Total number of reconciliation errors and terminal errors per controller.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "rate(controller_runtime_reconcile_errors_total{job=\"$job_name\",  controller=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "Errors"
      },
      {
       "expr": "rate(controller_runtime_terminal_reconcile_errors_total{job=\"$job_name\", controller=~\"$controller\"}[$__rate_interval])",
       "legendFormat": "Terminal Errors"
      }
     ]
    },
    {
     "title": "Max Concurrent Reconciles",
     "type": "timeseries",
     "description": "Number of concurrent reconciles per controller.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "controller_runtime_max_concurrent_reconciles{job=\"$job_name\", controller=~\"$controller\"}",
       "legendFormat": "{{controller}}"
      }
     ]
    },
    {
     "title": "Webhook Requests (rate) (total)",
     "type": "timeseries",
     "description": "Total number of admission requests by HTTP status code.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum by (code, webhook) (rate(controller_runtime_webhook_requests_total{job=\"$job_name\", webhook=~\".*$controller\"}[$__rate_interval]))",
       "legendFormat": "{{webhook}} / {{code}}"
      }
     ]
    },
    {
     "title": "Webhook In Flight Requests",
     "type": "timeseries",
     "description": "Current number of admission requests being\nserved.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum by (webhook) (controller_runtime_webhook_requests_in_flight{job=\"$job_name\", webhook=~\".*$controller\"})",
       "legendFormat": "{{webhook}}"
      }
     ]
    },
    {
     "title": "Rest Client Requests (rate) (total)",
     "type": "timeseries",
     "description": "Total number of REST client requests.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "sum by (code, method) (rate(rest_client_requests_total{job=~\"$job_name\", code=~\".*\"}[$__rate_interval]))",
       "legendFormat": "{{method}} / {{code}}"
      }
     ]
    }
   ]
  }
 ]
}