{
 "title": "Aerospike Outbound Connector View",
 "tags": [ "connectors" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "xdr_proxy_cluster_name",
    "label": "XDR Proxy Cluster Name",
    "query": {
     "query": "label_values(aerospike_xdr_proxy_jvm_gc_count, cluster_name)"
    }
   },
   {
    "name": "kafka_cluster_name",
    "label": "Kafka Cluster Name",
    "query": {
     "query": "label_values(aerospike_kafka_outbound_jvm_gc_count, cluster_name)"
    }
   },
   {
    "name": "pulsar_cluster_name",
    "label": "Pulsar Cluster Name",
    "query": {
     "query": "label_values(aerospike_pulsar_outbound_jvm_gc_count, cluster_name)"
    }
   },
   {
    "name": "jms_cluster_name",
    "label": "JMS Cluster Name",
    "query": {
     "query": "label_values(aerospike_jms_outbound_jvm_gc_count, cluster_name)"
    }
   },
   {
    "name": "elastic_cluster_name",
    "label": "Elastic Search Cluster Name",
    "query": {
     "query": "label_values(aerospike_elasticsearch_outbound_jvm_gc_count, cluster_name)"
    }
   },
   {
    "name": "esp_cluster_name",
    "label": "ESP Cluster Name",
    "query": {
     "query": "label_values(aerospike_esp_outbound_jvm_gc_count, cluster_name)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values( {__name__=~\"(.*)jvm_gc_count.*\"}, cluster_name) "
    }
   },
   {
    "name": "instance",
    "label": "Connector Instance",
    "query": {
     "query": "label_values( {cluster_name=~\"(.*)${cluster_name}.*\"}, instance) "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Display's all clusters for enabled or configured connectors , connector instance can be filtered using the cluster name and connector instance filter combination\n<br><b>Note</b>: if any cluster is not installed/enabled a default row is shown with empty panels and no data"
   }
  },
  {
   "title": "XDR Proxy - $xdr_proxy_cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "xdr_proxy_cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Connector Lag",
     "type": "stat",
     "description": "The lag between update of a record in Aerospike and it reaching the Connector. Output in milliseconds. Calculated as aerospike_record.lut - current_time. It's sampled every second based on the XDR record being processed at that time, it is approximate and not exact.\nReference: https://docs.aerospike.com/connect/streaming/management-api",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aerospike_xdr_proxy_requests_lag{cluster_name=~\"$xdr_proxy_cluster_name\"})"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_xdr_proxy_connections{cluster_name=~\"$xdr_proxy_cluster_name\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",status=\"error\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",status=\"success\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Parse Error (rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",status=\"skipped\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Skipped(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",status=\"skipped\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\",status=\"success\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Success"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Error"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records skipped.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\",status=\"skipped\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Skipped"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR record parsing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_xdr_proxy_requests{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\",status=\"parse-error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Parse Error"
      }
     ]
    },
    {
     "title": "Median Request Handling Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_xdr_proxy_requests_total{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"} * 1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Median Incoming XDR Record Size ",
     "type": "timeseries",
     "description": "Size of the incoming Aerospike XDR records in bytes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "aerospike_xdr_proxy_record_payload_size{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}\n",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Connector Lag",
     "type": "timeseries",
     "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_xdr_proxy_requests_lag{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{instance}} - Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "timeseries",
     "description": "Rate of Connections from Aerospike XDR to the connector.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_xdr_proxy_connections{cluster_name=~\"$xdr_proxy_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Connections rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka - $kafka_cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "kafka_cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Connector Lag",
     "type": "stat",
     "description": "Maximum lag in record LUT (last update time) in Aerospike and the record reaching the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aerospike_kafka_outbound_requests_lag{cluster_name=~\"$kafka_cluster_name\"})",
       "legendFormat": "Maximum Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "stat",
     "description": "Rate of Connections from Aerospike XDR to the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  ( \n    rate(aerospike_kafka_outbound_connections{cluster_name=~\"$kafka_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR records processing error.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",status=\"error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "stat",
     "description": "Total incoming XDR records successfully handled.",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",status=\"success\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Kafka Producer(rate)",
     "type": "stat",
     "description": "Total rate of Kafka Producer creation.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum ( \n    rate(aerospike_kafka_outbound_kafka_producers{cluster_name=~\"$kafka_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR record parsing error.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",status=\"parse-error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "stat",
     "description": "Total incoming XDR records skipped.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",status=\"skipped\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\",status=\"success\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Success"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Error"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records skipped.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\",status=\"skipped\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Skipped"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR record parsing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_kafka_outbound_requests{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\",status=\"parse-error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Parse"
      }
     ]
    },
    {
     "title": "Median Request Handling Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_kafka_outbound_requests_total{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}  * 1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Median Incoming XDR Record Size ",
     "type": "timeseries",
     "description": "Size of the incoming Aerospike XDR records in bytes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "aerospike_kafka_outbound_record_payload_size{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}\n",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Connector Lag",
     "type": "timeseries",
     "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_kafka_outbound_requests_lag{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{instance}} -Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "timeseries",
     "description": "Rate of Connections from Aerospike XDR to the connector.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_kafka_outbound_connections{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Connections"
      }
     ]
    },
    {
     "title": "Kafka Producers",
     "type": "timeseries",
     "description": "Rate of Kafka Producer creation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_kafka_outbound_kafka_producers{cluster_name=~\"$kafka_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Kafka Producers"
      }
     ]
    }
   ]
  },
  {
   "title": "Pulsar - $pulsar_cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "pulsar_cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Connector Lag",
     "type": "stat",
     "description": "Maximum lag in record LUT (last update time) in Aerospike and the record reaching the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aerospike_pulsar_outbound_requests_lag{cluster_name=~\"$pulsar_cluster_name\"})",
       "legendFormat": "Maximum Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "stat",
     "description": "Rate of Connections from Aerospike XDR to the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  ( \n    rate(aerospike_pulsar_outbound_connections{cluster_name=~\"$pulsar_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR records processing error.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",status=\"error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "stat",
     "description": "Total incoming XDR records successfully handled.",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",status=\"success\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Pulsar Producers(rate)",
     "type": "stat",
     "description": "Total rate of Pulsar producers creation.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum ( \n    rate(aerospike_pulsar_outbound_pulsar_producers{cluster_name=~\"$pulsar_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR record parsing error.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",status=\"parse-error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "stat",
     "description": "Total incoming XDR records skipped.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",status=\"skipped\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\",status=\"success\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Success"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Error"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records skipped.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\",status=\"skipped\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Skipped"
      }
     ]
    },
    {
     "title": "Parse(rate)",
     "type": "timeseries",
     "description": "Incoming XDR record parsing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_pulsar_outbound_requests{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\",status=\"parse-error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Parse"
      }
     ]
    },
    {
     "title": "Median Request Handling Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_pulsar_outbound_requests_total{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"} * 1000",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Median Incoming XDR Record Size ",
     "type": "timeseries",
     "description": "Size of the incoming Aerospike XDR records in bytes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "aerospike_pulsar_outbound_record_payload_size{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}\n",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Connector Lag",
     "type": "timeseries",
     "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_pulsar_outbound_requests_lag{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{instance}} -Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "timeseries",
     "description": "Rate of Connections from Aerospike XDR to the connector.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_pulsar_outbound_connections{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Connections"
      }
     ]
    },
    {
     "title": "Pulsar Producers(rate)",
     "type": "timeseries",
     "description": "Rate of Pulsar producers creation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_pulsar_outbound_pulsar_producers{cluster_name=~\"$pulsar_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Pulsar Producers"
      }
     ]
    }
   ]
  },
  {
   "title": "JMS - $jms_cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "jms_cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Connector Lag",
     "type": "stat",
     "description": "Maximum lag in record LUT (last update time) in Aerospike and the record reaching the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aerospike_jms_outbound_requests_lag{cluster_name=~\"$jms_cluster_name\"})",
       "legendFormat": "Maximum Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "stat",
     "description": "Rate of Connections from Aerospike XDR to the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  ( \n    rate(aerospike_jms_outbound_connections{cluster_name=~\"$jms_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR records processing error.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",status=\"error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "stat",
     "description": "Total incoming XDR records successfully handled.",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",status=\"success\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "JMS Outbound Connections(rate)",
     "type": "stat",
     "description": "Total rate of JMS connections creation.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum ( \n    rate(aerospike_jms_outbound_jms_connections{cluster_name=~\"$jms_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR record parsing error.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",status=\"parse-error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "stat",
     "description": "Total incoming XDR records skipped.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",status=\"skipped\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\",status=\"success\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Success"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Error"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records skipped.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\",status=\"skipped\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Skipped"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR record parsing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_jms_outbound_requests{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\",status=\"parse-error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Parse"
      }
     ]
    },
    {
     "title": "Median Request Handling Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_jms_outbound_requests_total{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}  * 1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Median Incoming XDR Record Size ",
     "type": "timeseries",
     "description": "Size of the incoming Aerospike XDR records in bytes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "aerospike_jms_outbound_record_payload_size{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}\n",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Connector Lag",
     "type": "timeseries",
     "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_jms_outbound_requests_lag{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{instance}} -Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "timeseries",
     "description": "Rate of Connections from Aerospike XDR to the connector.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_jms_outbound_connections{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Connections"
      }
     ]
    },
    {
     "title": "JMS Connections(rate)",
     "type": "timeseries",
     "description": "Rate of JMS connections creation.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_jms_outbound_jms_connections{cluster_name=~\"$jms_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -JMS Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Elastic search - $elastic_cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "elastic_cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Connector Lag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aerospike_elasticsearch_outbound_requests_lag{cluster_name=~\"$elastic_cluster_name\"})"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "stat",
     "description": "Rate of Connections from Aerospike XDR to the connectors.",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  ( \n    rate(aerospike_elasticsearch_outbound_connections{cluster_name=~\"$elastic_cluster_name\"}[$__rate_interval])\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR records processing error.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",status=\"error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "stat",
     "description": "Total incoming XDR records successfully handled.",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",status=\"success\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "stat",
     "description": "Total incoming XDR record parsing error.",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",status=\"parse-error\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "stat",
     "description": "Total incoming XDR records skipped.",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",status=\"skipped\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\",status=\"success\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Success"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\",status=\"error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Error"
      }
     ]
    },
    {
     "title": "Skip(rate)",
     "type": "timeseries",
     "description": "Incoming XDR records skipped.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\",status=\"skipped\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Skipped"
      }
     ]
    },
    {
     "title": "Parse(rate)",
     "type": "timeseries",
     "description": "Incoming XDR record parsing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_elasticsearch_outbound_requests{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\",status=\"parse-error\"}[$__rate_interval])",
       "legendFormat": "{{instance}} -Parse"
      }
     ]
    },
    {
     "title": "Median Request Handling Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_elasticsearch_outbound_requests_total{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"} * 1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Median Incoming XDR Record Size ",
     "type": "timeseries",
     "description": "Size of the incoming Aerospike XDR records in bytes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "aerospike_elasticsearch_outbound_record_payload_size{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\",quantile=\"0.5\"}\n",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Connector Lag",
     "type": "timeseries",
     "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_elasticsearch_outbound_requests_lag{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{instance}} -Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "timeseries",
     "description": "Rate of Connections from Aerospike XDR to the connector.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_elasticsearch_outbound_connections{cluster_name=~\"$elastic_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "ESP - $esp_cluster_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "esp_cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Connector Lag",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(aerospike_esp_outbound_requests_lag{cluster_name=~\"$esp_cluster_name\"})"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_esp_outbound_connections{cluster_name=~\"$esp_cluster_name\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_esp_outbound_requests{cluster_name=~\"$esp_cluster_name\",status=\"error\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_esp_outbound_requests{cluster_name=~\"$esp_cluster_name\",status=\"success\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Skipped(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_esp_outbound_requests{cluster_name=~\"$esp_cluster_name\",status=\"skipped\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Parse Error(rate)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_esp_outbound_requests{cluster_name=~\"$esp_cluster_name\",status=\"skipped\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Success(rate)",
     "type": "timeseries",
     "description": "Rate of successfully handled incoming change notification requests.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_esp_outbound_requests{status=\"success\",cluster_name=~\"$esp_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Success "
      }
     ]
    },
    {
     "title": "Error(rate)",
     "type": "timeseries",
     "description": "Rate of failed  incoming change notification requests.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_esp_outbound_requests{status=\"error\",cluster_name=~\"$esp_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])",
       "legendFormat": "{{instance}} - Error "
      }
     ]
    },
    {
     "title": "Median Request Handling Time",
     "type": "timeseries",
     "description": "Incoming change notification median request handling time.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_esp_outbound_requests_total{quantile=\"0.5\",instance=~\"${instance:pipe}\",cluster_name=~\"$esp_cluster_name\"} * 1000",
       "legendFormat": "{{instance}} - Median Request Handling Time"
      }
     ]
    },
    {
     "title": "Destination Queue Size",
     "type": "timeseries",
     "description": "Per destination, per target endpoint (host,port) queue sizes.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance,destination,destination_endpoint) (aerospike_esp_outbound_destination_requests{status=\"queued\", instance=~\"${instance:pipe}\", cluster_name=\"$esp_cluster_name\"})",
       "legendFormat": "Queued {{instance}} [{{destination}}/{{destination_endpoint}}]"
      }
     ]
    },
    {
     "title": "Destination Success(rate)",
     "type": "timeseries",
     "description": "Rate of successfully delivered incoming change notification requests for each destination.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (destination,instance) (rate(aerospike_esp_outbound_destination_requests{status=\"success\", instance=~\"${instance:pipe}\",cluster_name=~\"$esp_cluster_name\"}[$__rate_interval]))",
       "legendFormat": "Success {{instance}} [{{destination}}]"
      }
     ]
    },
    {
     "title": "Destination Error(rate)",
     "type": "timeseries",
     "description": "Rate of failed incoming change notification requests for each destination.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (destination,instance) (rate(aerospike_esp_outbound_destination_requests{status=\"error\", instance=~\"${instance:pipe}\", cluster_name=~\"$esp_cluster_name\"}[$__rate_interval]))",
       "legendFormat": "Success {{instance}} [{{destination}}]"
      }
     ]
    },
    {
     "title": "Health Check Success(rate)",
     "type": "timeseries",
     "description": "Rate of health check successes for each destination.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (destination,instance) (rate(aerospike_esp_outbound_health_check{status=\"success\", instance=~\"${instance:pipe}\",cluster_name=~\"$esp_cluster_name\"}[$__rate_interval]))",
       "legendFormat": "Success {{instance}} [{{destination}}]"
      }
     ]
    },
    {
     "title": "Health Check Error(rate)",
     "type": "timeseries",
     "description": "Rate of health check failures for each destination.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (destination,instance) (rate(aerospike_esp_outbound_health_check{status=\"error\",instance=~\"${instance:pipe}\",cluster_name=~\"$esp_cluster_name\"}[$__rate_interval]))",
       "legendFormat": "Success {{instance}} [{{destination}}]"
      }
     ]
    },
    {
     "title": "Connector Lag",
     "type": "timeseries",
     "description": "Lag in record LUT (last update time) in Aerospike and the record reaching the connector.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_esp_outbound_requests_lag{cluster_name=~\"$esp_cluster_name\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{instance}} -Lag"
      }
     ]
    },
    {
     "title": "Connections(rate)",
     "type": "timeseries",
     "description": "Rate of Connections from Aerospike XDR to the connector.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) ( \n    rate(aerospike_esp_outbound_connections{cluster_name=~\"$esp_cluster_name\",instance=~\"${instance:pipe}\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}} -Connections"
      }
     ]
    }
   ]
  }
 ]
}