{
 "title": "Aerospike Connectors JVM",
 "tags": [
  "connectors",
  "jvm",
  "node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "connector_type",
    "label": "connector_type",
    "query": {
     "query": "query_result( label_join( label_replace( label_replace( label_replace( label_join( {__name__=~\".*jvm_gc_count\"},\"connector_type\",\",\", \"__name__\" ), \"connector_type\", \"$1\" , \"connector_type\", \"aerospike.([^.]*)\" ),\"connector_type\", \"$1\" ,\"connector_type\",\"(.*)_jvm_gc_count.*\"),\"connector_type_pfx\",\"$1\",\"connector_type\",\"(.*)_.*\"),\"new_cluster_name\", \" - \", \"connector_type_pfx\", \"cluster_name\" ) )"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values( {__name__=~\"(.*)${connector_type}.*\"}, cluster_name) "
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values( {__name__=~\"(.*)${connector_type}.*\", cluster_name=~\"(.*)${cluster_name}.*\"}, instance) "
    }
   },
   {
    "name": "instance2",
    "label": "Instance",
    "query": {
     "query": "query_result( label_join( label_replace( label_replace( label_replace( label_join( {__name__=~\".*jvm_gc_count\"},\"connector_type\",\",\", \"__name__\" ), \"connector_type\", \"$1\" , \"connector_type\", \"aerospike.([^.]*)\" ),\"connector_type\", \"$1\" ,\"connector_type\",\"(.*)_jvm_gc_count.*\"),\"connector_type_pfx\",\"$1\",\"connector_type\",\"(.*)_.*\"),\"new_cluster_name\", \" --> |\",  \"connector_type\", \"instance\") )"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime(max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_${connector_type}_jvm_attribute_uptime{cluster_name=~\"$cluster_name\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Process CPU Used(max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_${connector_type}_jvm_os_processCpuLoad{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "System CPU Used(max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_${connector_type}_jvm_os_systemCpuLoad{cluster_name=~\"$cluster_name\", instance=~\"$instance\"} )*100"
    }
   ]
  },
  {
   "title": "% Heap used(max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_${connector_type}_jvm_memory_heap_used{cluster_name=~\"$cluster_name\",instance=~\"$instance\"}*100/aerospike_${connector_type}_jvm_memory_heap_max{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "% Non Heap used(max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_${connector_type}_jvm_memory_non_heap_used{cluster_name=~\"$cluster_name\",instance=~\"$instance\"}*100/aerospike_${connector_type}_jvm_memory_non_heap_max{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "$connector_type - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage - System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_${connector_type}_jvm_os_systemCpuLoad{cluster_name=~\"$cluster_name\", instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Process",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_${connector_type}_jvm_os_processCpuLoad{cluster_name=~\"$cluster_name\", instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Process (1 hour avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(aerospike_${connector_type}_jvm_os_processCpuLoad{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$connector_type - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Collections(rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(aerospike_${connector_type}_jvm_gc_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{gc}}"
      }
     ]
    },
    {
     "title": "GC Duration(rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(aerospike_${connector_type}_jvm_gc_time{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}[1m])/rate(aerospike_${connector_type}_jvm_gc_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} {{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$connector_type - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap - Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_heap_used{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Non-Heap - Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_non_heap_used{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap - Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_heap_max{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Non-Heap - Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_non_heap_max{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap - Committed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_heap_committed{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Non-Heap - Commited",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_non_heap_committed{cluster_name=~\"$cluster_name\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total - Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_total_used{cluster_name=~\"$cluster_name\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total - Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_total_max{cluster_name=~\"$cluster_name\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total - Commited",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_${connector_type}_jvm_memory_total_committed{cluster_name=~\"$cluster_name\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$connector_type - Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads - Live",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_threads_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\", state=\"runnable\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads - Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_threads_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads - Daemon",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_threads_daemon_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads - Peak",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_threads_peak_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_threads_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}} {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$connector_type - FD & Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors - Open",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_files_open{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "File Descriptors - Max",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_files_max{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_classloader_loaded{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(aerospike_${connector_type}_jvm_classloader_loaded{cluster_name=~\"$cluster_name\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$connector_type - Buffers ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers - Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_buffers_direct_used{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers - Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_buffers_mapped_used{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Direct Buffer Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_buffers_direct_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped Buffer Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_buffers_mapped_count{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Direct Buffers - Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_buffers_direct_capacity{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers - Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_${connector_type}_jvm_buffers_mapped_capacity{cluster_name=~\"$cluster_name\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}