{
 "title": "Aerospike Backup Service",
 "description": "This dashboard helps to visualise the aerospike backup service statistics.",
 "tags": [
  "aerospike",
  "monitoring",
  "Backup"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_backup_service_runs_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aerospike_backup_service_runs_total{job=~\"$job_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services (count)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (aerospike_backup_service_runs_total{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runs Count (Total)",
   "type": "stat",
   "description": "Total backup runs, \nTotal  incremental  backup runs.",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(aerospike_backup_service_runs_total{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Full"
    },
    {
     "expr": " sum(aerospike_backup_service_incremental_runs_total{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Incremental"
    }
   ]
  },
  {
   "title": "Failures Count (Total)",
   "type": "stat",
   "description": "Total backup failures, \nTotal  incremental  backup failures.",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(aerospike_backup_service_failure_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Full"
    },
    {
     "expr": " sum(rate(aerospike_backup_service_incremental_failure_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Incremental"
    }
   ]
  },
  {
   "title": "Skip Count (Total)",
   "type": "stat",
   "description": "Total backup skip, \nTotal  incremental  backup skip.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(aerospike_backup_service_skip_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Full"
    },
    {
     "expr": " sum(rate(aerospike_backup_service_incremental_skip_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Incremental"
    }
   ]
  },
  {
   "title": "Duration (ms)",
   "type": "stat",
   "description": "Full backup duration in milliseconds,\nIncremental backup duration in milliseconds.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_backup_service_duration_millis{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Full"
    },
    {
     "expr": "sum(aerospike_backup_service_incremental_duration_millis{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "Incremental"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Runs Count (Total)",
     "type": "stat",
     "description": "Total backup runs, \nTotal  incremental  backup runs.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(aerospike_backup_service_runs_total{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "Full"
      },
      {
       "expr": " sum(aerospike_backup_service_incremental_runs_total{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "Incremental"
      }
     ]
    },
    {
     "title": "Failures Count (Total)",
     "type": "stat",
     "description": "Total backup failures, \nTotal  incremental  backup failures.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(rate(aerospike_backup_service_failure_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Full"
      },
      {
       "expr": " sum(rate(aerospike_backup_service_incremental_failure_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Incremental"
      }
     ]
    },
    {
     "title": "Skip Count (Total)",
     "type": "stat",
     "description": "Total backup skip, \nTotal  incremental  backup skip.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(rate(aerospike_backup_service_skip_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Full"
      },
      {
       "expr": " sum(rate(aerospike_backup_service_incremental_skip_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Incremental"
      }
     ]
    },
    {
     "title": "Duration (ms)",
     "type": "stat",
     "description": "Full backup duration in milliseconds,\nIncremental backup duration in milliseconds.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_backup_service_duration_millis{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "Full"
      },
      {
       "expr": "sum(aerospike_backup_service_incremental_duration_millis{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "Incremental"
      }
     ]
    },
    {
     "title": "Full Runs (rate)",
     "type": "timeseries",
     "description": "Total backup runs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_runs_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Incremental Runs (rate)",
     "type": "timeseries",
     "description": "Total Incremental backup runs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_incremental_runs_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Full Duration (ms)",
     "type": "timeseries",
     "description": " Full backup duration in milliseconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(aerospike_backup_service_duration_millis{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": " Incremental Duration (ms)",
     "type": "timeseries",
     "description": "Total Incremental backup duration in milliseconds",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(aerospike_backup_service_incremental_duration_millis{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Full Failures (rate)",
     "type": "timeseries",
     "description": "Total Backup failures.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_failure_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Incremental Failures (rate)",
     "type": "timeseries",
     "description": "Total Incremental backup failures.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_incremental_failure_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Full Skip (rate)",
     "type": "timeseries",
     "description": "Total backup skipped.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_skip_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Incremental Skip  (rate)",
     "type": "timeseries",
     "description": "Total Incremental backup skipped.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_backup_service_incremental_skip_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    }
   ]
  }
 ]
}