# labels to add to the prometheus metrics for e.g. labels={zone="asia-south1-a", platform="google compute engine"}

[Agent]
cert_file = ""
key_file = ""
root_ca = ""
key_file_passphrase = ""
labels = {type="development",source="aerospike",latitude="41.8780",longitude="-93.0977"}
bind = ":9145"
timeout = 10
log_file = ""
log_level = ""
basic_auth_username = ""
basic_auth_password = ""
[Aerospike]
db_host = "localhost"
db_port = 3000
root_ca = ""
cert_file = ""
key_file = ""
key_file_passphrase = ""
node_tls_name = ""
user = ""
password = ""
auth_mode = ""
timeout = 5
latency_buckets_count = 0