{
 "title": "Aerospike Graph Service JVM",
 "description": "dashboard display key java-virtual-machine metrics like Memory, CPU, Memory, Threads, Classes, File-Descriptors and Buffers. Each group of metric is shown in individual rows",
 "tags": [
  "graph",
  "monitoring",
  "usecases",
  "jvm",
  "node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_graph_service_jvm_info,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Aerospike Cluster",
    "query": {
     "query": "label_values(aerospike_graph_service_cluster_name{job=~\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aerospike_graph_service_cluster_name{job=~\"$job_name\", cluster_name=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance (count)",
   "type": "stat",
   "description": "Healthy - Green",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "neo4j_instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aerospike_graph_service_jvm_info{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% Heap Used (max)",
   "type": "stat",
   "description": "The maximum heap used memory.",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((aerospike_graph_service_jvm_memory_bytes_used{job=~\"$job_name\", instance=~\"$instance\", area=~\"heap\"})*100 / (aerospike_graph_service_jvm_memory_bytes_max{job=~\"$job_name\", instance=~\"$instance\", area=~\"heap\"}))",
     "legendFormat": "Heap used max"
    }
   ]
  },
  {
   "title": "Current Threads(total)",
   "type": "stat",
   "description": "Current count of JVM threads.",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_graph_service_jvm_threads_current{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "current threads"
    }
   ]
  },
  {
   "title": "Objects waiting",
   "type": "bargauge",
   "description": "The number of objects waiting in the finalizer queue.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Aerospike Cluster name",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " group by (cluster_name)(aerospike_graph_service_cluster_name{job=~\"$job_name\", cluster_name=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "JVM version",
     "type": "stat",
     "description": "VM version info",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_info{job=~\"$job_name\",instance=~\"$instance\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Used memory",
     "type": "gauge",
     "description": "Used bytes of a given JVM memory area",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_used{job=~\"$job_name\", instance=~\"$instance\", area=~\".*\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "stat",
     "description": "Total Loaded - The total number of classes that have been loaded since the JVM has started execution.\n\nCurrently Loaded - The number of classes that are currently loaded in the JVM.\n\nTotal Unloaded - The total number of classes that have been unloaded since the JVM has started execution.\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_loaded_total{job=~\"$job_name\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Total Loaded"
      },
      {
       "expr": "aerospike_graph_service_jvm_classes_currently_loaded{job=~\"$job_name\",instance=~\"$instance\"}",
       "legendFormat": "Currently Loaded"
      },
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_unloaded_total{job=~\"$job_name\",instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Total Unloaded"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Threads</b></p>"
     }
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Current, Daemon, peak, started thread count of a JVM.\nDeadlocked - Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_threads_current{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "current"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_daemon{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "daemon"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_peak{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "peak"
      },
      {
       "expr": "rate(aerospike_graph_service_jvm_threads_started_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "started"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_deadlocked{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "deadlocked"
      },
      {
       "expr": "(aerospike_graph_service_jvm_threads_deadlocked_monitor{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "deadlocked_monitor"
      }
     ]
    },
    {
     "title": "Threads state",
     "type": "timeseries",
     "description": "Current count of threads by state.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_threads_state{job=~\"$job_name\", instance=~\"$instance\" })",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Memory</b></p>"
     }
    },
    {
     "title": "Committed memory (bytes)",
     "type": "timeseries",
     "description": "Committed (bytes) of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_committed{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Initial memory (bytes)",
     "type": "timeseries",
     "description": "Initial bytes of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_init{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Max memory (bytes)",
     "type": "timeseries",
     "description": "Max (bytes) of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_max{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "title": "Used memory (bytes)",
     "type": "timeseries",
     "description": "Used bytes of a given JVM memory area.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_bytes_used{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{area}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Memory Pool</b></p>"
     }
    },
    {
     "title": "Allocated (bytes)(rate)",
     "type": "timeseries",
     "description": "Total bytes allocated in a given JVM memory pool",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_memory_pool_allocated_bytes_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Created (bytes)(rate)",
     "type": "timeseries",
     "description": "Total bytes allocated in a given JVM memory pool. Only updated after GC, not continuously.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_memory_pool_allocated_bytes_created{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Initial (bytes)",
     "type": "timeseries",
     "description": "Initial bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_init{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Committed (bytes)",
     "type": "timeseries",
     "description": "Committed bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_committed{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Used (bytes)",
     "type": "timeseries",
     "description": "Used bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_used{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Max (bytes)",
     "type": "timeseries",
     "description": "Max bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_bytes_max{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Memory Pool Collection</b></p>"
     }
    },
    {
     "title": "Init (bytes)",
     "type": "timeseries",
     "description": "Initial after last collection bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_init_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Committed (bytes)",
     "type": "timeseries",
     "description": "Committed after last collection bytes of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_committed_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Used (bytes)",
     "type": "timeseries",
     "description": "Used bytes after last collection of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_used_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Max (bytes)",
     "type": "timeseries",
     "description": "Max bytes after last collection of a given JVM memory pool.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_pool_collection_max_bytes{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Objects</b></p>"
     }
    },
    {
     "title": "Load",
     "type": "timeseries",
     "description": "Total Loaded - The total number of classes that have been loaded since the JVM has started execution.\n\nTotal Unloaded - The total number of classes that have been unloaded since the JVM has started execution.\n\nCurrently Loaded - The number of classes that are currently loaded in the JVM.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_loaded_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "loaded"
      },
      {
       "expr": "rate(aerospike_graph_service_jvm_classes_unloaded_total{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "Unloaded"
      },
      {
       "expr": "aerospike_graph_service_jvm_classes_currently_loaded{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Objects waiting",
     "type": "timeseries",
     "description": "The number of objects waiting in the finalizer queue.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(aerospike_graph_service_jvm_memory_objects_pending_finalization{job=~\"$job_name\", instance=~\"$instance\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 72 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Buffer Pool</b></p>"
     }
    },
    {
     "title": "Used bytes",
     "type": "timeseries",
     "description": "Used bytes of a given JVM buffer pool.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_buffer_pool_used_bytes{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Used buffers",
     "type": "timeseries",
     "description": "Used buffers of a given JVM buffer pool.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_buffer_pool_used_buffers{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Bytes Capacity",
     "type": "timeseries",
     "description": "Bytes capacity of a given JVM buffer pool.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_graph_service_jvm_buffer_pool_capacity_bytes{job=~\"$job_name\", instance=~\"$instance\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
     "options": {
      "content": "<p style=\"text-align:center;background-color:rgb(31, 96, 196);font-size:20px\"><b>Garbage Collector</b></p>"
     }
    },
    {
     "title": "GC count (rate)",
     "type": "timeseries",
     "description": "Time spent in a given JVM garbage collector in seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_gc_collection_seconds_count{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC sum (rate)",
     "type": "timeseries",
     "description": "Time spent in a given JVM garbage collector in seconds",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(aerospike_graph_service_jvm_gc_collection_seconds_sum{job=~\"$job_name\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  }
 ]
}