groups:
- name: secret_agent.rules
  rules:
  - alert: AerospikeSecretAgentDown
    expr: absent(aerospike_sa_connections_active{job="aerospike_secret_agent"}) == 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Aerospike Secret Agent instance {{ $labels.instance }} in cluster {{$labels.cluster_name}} has been down for more than 1m."
      description: "Aerospike Secret Agent instance {{ $labels.instance }} in cluster {{$labels.cluster_name}} has been down for more than 1m."

