# docker-compose.yml
version: '3.8'

services:
  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server-enterprise:latest
#    volumes:
#      - .:/etc/aerospike
#      - "./aerospike.conf:/etc/aerospike/aerospike.conf"
#    command: [ "--config-file","/etc/aerospike/aerospike.conf" ]
    ports:
      - "3000:3000"

  aerospike_tools:
    container_name: aerospiketools
    image: aerospike/aerospike-tools:latest
    depends_on:
      - aerospike
    command: [asadm, -haerospike]
    stdin_open: true



  exporter1:
   image: aerospike/aerospike-prometheus-exporter:latest

   container_name: exporter1
   environment:
    - AS_HOST=host.docker.internal
    - AS_PORT=3000
    - "METRIC_LABELS=type='development',source='aerospike'"

   ports:
    - "9145:9145"



  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus
    volumes:
      - source: prometheus_data
        target: /var/lib/prometheus/
        type: volume
      - source: ./easy-prometheus.yml
        target: /etc/prometheus/prometheus.yml
        type: bind
      - source: ./config/prometheus/aerospike_rules.yml
        target: /etc/prometheus/aerospike_rules.yml
        type: bind
    depends_on:
      - exporter1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  alertmanager:
    image: prom/alertmanager

    container_name: alertmanager
    volumes:
      - source: alertmanager_data
        target: /alertmanager
        type: volume
      - source: ./config/prometheus/alertmanager.yml
        target: /etc/prometheus/alertmanager.yml
        type: bind
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:latest

    container_name: grafana
    volumes:
      - source: grafana_data
        target: /var/lib/grafana
        type: volume
      - source: ./config/grafana/dashboards/
        target: /var/lib/grafana/dashboards/
        type: bind
      - source: ./config/grafana/provisioning/
        target: /etc/grafana/provisioning/
        type: bind
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource
    depends_on:
      - prometheus
    ports:
      - "4000:3000"

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}