name: Create tar.gz artifacts of dashboards

on: 
  push:
    tags:
       - v*

permissions:
  id-token: write
  actions: write
  contents: write

jobs:         
    tar_zipping_and_sign_job:
      runs-on: ubuntu-22.04
      steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
          with:
            egress-policy: audit

        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        - uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
          id: get-latest-tag

        - name: Set up GPG for signing
          uses: aerospike/shared-workflows/.github/actions/setup-gpg@8f53b63b33d86e63aeb37d951283dd974574885b
          with:
            gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
            gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
            gpg-key-pass: ${{ secrets.GPG_PASS }}
          
        - name: Create tar files and Sign packages
          env:
            GH_TOKEN: ${{ github.token }}
            TAG_NAME: "${{ steps.get-latest-tag.outputs.tag }}"
            GPG_TTY: no-tty
            HOME: /home/runner
            GNUPGHOME: /home/runner/.gnupg
            GPG_PASS: ${{ secrets.GPG_PASS }}
          run: |
            cd config/grafana
            # TAG_NAME format v20.0.0 - remove the 'v'
            # we move ams with plain veraion number like ams...20.0.0.tar.ga
            AMS_ARTEFACT_NAME="aerospike-grafana-dashboards-${TAG_NAME#v}.tar.gz"

            # tar, sign and upload
            tar czf $AMS_ARTEFACT_NAME dashboards/*

            echo "Generating sha256 and asc for $AMS_ARTEFACT_NAME"
            sha256sum "$AMS_ARTEFACT_NAME" > "$AMS_ARTEFACT_NAME.sha256"
              
            # asc for tgz
            gpg --armour --detach-sign \
                  --no-tty --batch --yes \
                  --passphrase "$GPG_PASS" \
                  --pinentry-mode loopback \
                  --local-user aerospike-inc \
                  --output "$AMS_ARTEFACT_NAME.asc" "$AMS_ARTEFACT_NAME"  

            gpg --armour --detach-sign \
                  --no-tty --batch --yes \
                  --passphrase "$GPG_PASS" \
                  --pinentry-mode loopback \
                  --local-user aerospike-inc \
                  --output "$AMS_ARTEFACT_NAME.sha256.asc" "$AMS_ARTEFACT_NAME.sha256"  
                  
            echo
            echo "Uploading release asset - tar.gz, tar.gz.asc tar.sha256"
            gh release upload "$TAG_NAME" "$AMS_ARTEFACT_NAME*"
            