name: Docker Datadog Aerospike Enterprise Agent Integration 

on:
  workflow_dispatch:
    inputs:
      docker_tag: 
         description: Docker Tag
         required: false
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Get latest release tag
      uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
      id: get-latest-tag

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Set up Docker Buildx
      uses: step-security/setup-buildx-action@a4709e2865773e1792246433e8eb922f9743a875 # v4.2.0

    - name: Docker login
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      env:
        DOCKER_MULTI_ARCH_PLATFORMS: linux/amd64,linux/arm64
      run: |
        VERSION_TAG=$(echo "${{ github.event.inputs.docker_tag }}" | xargs)

        if [ -n "$VERSION_TAG" ]; then

            echo "Using tag version $VERSION_TAG"
            docker buildx build --build-arg VERSION=$VERSION_TAG \
                  --platform $DOCKER_MULTI_ARCH_PLATFORMS \
                  --push . -f build/datadog.Dockerfile \
                  -t aerospike/datadog-aerospike-integration:latest \
                  -t aerospike/datadog-aerospike-integration:$VERSION_TAG
        fi 
