name: Docker Datadog Aerospike Enterprise Agent Integration 

on:
  workflow_dispatch:
    inputs:
      docker_tag: 
         description: Docker Tag
         required: false
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Get latest release tag
      uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
      id: get-latest-tag

    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: Set up Docker Buildx
      uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0

    - name: Docker login
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      env:
        DOCKER_MULTI_ARCH_PLATFORMS: linux/amd64,linux/arm64
      run: |
        VERSION_TAG=$(echo "${{ github.event.inputs.docker_tag }}" | xargs)

        if [ -n "$VERSION_TAG" ]; then

            echo "Using tag version $VERSION_TAG"
            docker buildx build --build-arg VERSION=$VERSION_TAG \
                  --platform $DOCKER_MULTI_ARCH_PLATFORMS \
                  --push . -f build/datadog.Dockerfile \
                  -t aerospike/datadog-aerospike-integration:latest \
                  -t aerospike/datadog-aerospike-integration:$VERSION_TAG
        fi 
