name: aerospike dashboard linter

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: '3.10' 

    - name: Install 
      run: pip3 install check-jsonschema

    - name: validate all json files against dashboard_schema.json
      run: |
         json_files=$(find ./config/grafana/dashboards -type f -name "*.json" -printf "$(realpath -s %p) ")
         
         for file in $json_files; do
           echo "validating file === $file"
           #  ok -- validation done if all is good, else returns error
           check-jsonschema --schemafile=build/dashboard_schema.json $file 
         done
